### ISSUE TITLE
Model optimizer with constant node

### ISSUE THREAD

**Issue by jiangmenghua** [openvinotoolkit/model_server#101]
Hi,
I do realize that openvino automatically removes a constant node that does nothing to the computation. However, for my project I would need a constant node that records information about the network, e.g. having attributes of lists of strings. Is there anyway I could embed a constant node in the network?

Thank you .

**Comment by dtrawins** [comment]
@jiangmenghua I think it might be the best to file this question to the developer zone related to OpenVINO toolkit https://software.intel.com/en-us/forums/computer-vision
It might be useful to include information why those constant attributes are needed in the network.
Perhaps any metadata related to the model should be stored outside of the model files?

**Comment by rasapala** [comment]
Not related to OVMS. Delegated to computer-vision support.
