### ISSUE TITLE
example_client/rest_binary_client.py failed

### ISSUE THREAD

**Issue by wfchair** [openvinotoolkit/model_server#1042]
Did anybody use model server rest binary api successfully? It always failed.

$ python rest_binary_client.py --model_name od
Start processing:
	Model name: od
	Images list file: input_images.txt
Server returned error: {u'error': u'Could not parse instance content. Not valid ndarray detected'}

**Comment by michalkulakowski** [comment]
Could you try to use client with any other format than default which is row_noname? To specify request format use --request_format flag. Supported formats are row_name, column_noname and column_name.

**Comment by wfchair** [comment]
python rest_binary_client.py --model_name od --request_format 'row_name'
Start processing:
	Model name: od
	Images list file: input_images.txt
Server returned error: {u'error': u'Could not parse instance content. Not valid ndarray detected'}

**Comment by michalkulakowski** [comment]
Which version of OVMS are you using?

**Comment by wfchair** [comment]
./ovms --version
OpenVINO Model Server 2021.3.c9ba5cfa
OpenVINO backend 2021.3.394

**Comment by michalkulakowski** [comment]
You should try to use this client with OVMS 2021.4 because binary inputs feature was introduced in release 2021.4
