### ISSUE TITLE
model_zoo_intel_object_detection custom node wrong NODE_ASSERT and label_ids output cleanup

### ISSUE THREAD

**Issue by mkuczyns11** [openvinotoolkit/model_server#1044]
In case label_ids output copying fails, custom node is responsible for all earlier allocated outputs cleanup. Therefore when `copy_label_ids_into_output(&labelIdsTensor, labelIds)` fails custom node should cleanup imagesTensor, coordinatesTensor and confidencesTensor instead of labelIdsTensor, which is not allocated.
During `getOutputsInfo()` function 4th output info allocation is not checked correctly. NODE_ASSERT should be called with `(*info)[3].dims` instead of `(*info)[2].dims`

**Comment by mkuczyns11** [comment]
This PR should fix above mentioned problems - https://github.com/openvinotoolkit/model_server/pull/1037.

**Comment by rasapala** [comment]
Fixed.
