### ISSUE TITLE
Classify and Regress API support?

### ISSUE THREAD

**Issue by clarkttfu** [openvinotoolkit/model_server#1193]
I found there is no Classify or Regress API comparing to TF Serving API, which i s confirmed in [this page](https://docs.openvino.ai/cn/latest/openvino_docs_ovms.html). If that is still the truth, is there any plan or roadmap to support those APIs?

Thanks,
Clark

**Comment by mzegla** [comment]
Hi Clark,

We do not support Classify and Regress APIs and there's no plan to add such support any time soon. 
Is Predict API insufficient for your use case?

**Comment by clarkttfu** [comment]
Hi, thanks for the reply!
I'm working on a solution to support as many TF models as possible.
To be honest, I'm not sure if our clients would need Classify or Regress API, just in case..

**Comment by mzegla** [comment]
Yeah, Predict API is the most general. It simply passes the input data from request to OpenVINO Inference Engine and returns results of the prediction in the response.
Classify and Regress might be convenient to use in some cases, but both of this tasks can be done with a simple postprocessing on the client side.

For TF models support, OVMS will support any model that is supported by OpenVINO, so if your TF -> OV conversion was successful and you can use the model directly with OpenVINO, then you can use it with OpenVINO Model Server as well.

**Comment by clarkttfu** [comment]
Thanks for the info, very helpful.
