### ISSUE TITLE
how to do batch predictions in openvino model server?

### ISSUE THREAD

**Issue by yuguanxiang** [openvinotoolkit/model_server#1207]
how to do batch predirections in openvino server?

i’ve a DeepFM model in video recommendation system, i trained the model in tensorflow, and provide online serving by tensorflow serving currently.
in tensorflow serving, i use http rest api to do batch prediction(batch size maybe any number in [100,1000])
//in tensorflow serving, i use curl to do http request to tensorflow serving (here for demostration, i send batch(size=2) request)
 _curl -X POST http://172.24.72.2:9601/v1/models/ctrdeepfm/versions/9037:predict –d ‘
 {
 	“instances”: [
           { “feat_ids”:[7,58,....], //1*301 vector
            “feat_vals”:[1.0,1.0,...], //1*301 vector
           },
           { “feat_ids”:[7,58,....], //1*301 vector
            “feat_vals”:[1.0,1.0,...], //1*301 vector
           }
     ]
 }
 ‘_

 //output, get 2 scores
_{
    "predictions": [0.0528144817, 0.0528254332
    ]
}_

here, i tried use openvino (openvino_2021.4.752) & model server , expecting to accelerate prediction , reduce predict latency,

1. run model optimizer and convert the model to  get IR
_python mo.py --log_level=DEBUG --input "feat_ids,feat_vals" --input_shape "[1,301],[1,301]" --saved_model_dir /tmp/1647427562/ --output_dir /tmp/1647427562out_
[root@Router_A model_optimizer]# ls /tmp/1647427562out
saved_model.bin  saved_model.mapping  saved_model.xml_

2.Then, i start openvino model server
_docker pull openvino/model_server
docker run -d -u $(id -u):$(id -g) -v $(pwd)/model_1647427562out:/models/deepfm -p 9000:9000 openvino/model_server:latest \
        --shape auto\
        --model_path /models/deepfm --model_name deepfm --rest_port 9000 --plugin_config '{"CPU_THROUGHPUT_STREAMS": "1"}'_

3. i send one prediction(batchsize=1) in one requet to model server, i get correct response
_curl -X POST http://10.2.177.40:9000/v1/models/deepfm/versions/1:predict -d '
{
"instances":[
{"feat_ids":[7,58,251,....],
"feat_vals":[1.0,1.0,1.0,...]
}
]
}'_ 

//output
_{
    "predictions": [
        {
            "Reshape_14": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            "CTR_PDT": 0.0529434271,
            "Multi-Head-Attention-Layer/Sum_1": -0.0317770354
        }
    ]
}_

4. i send two predictions(batchsize=2) in one request to model server
_curl -X POST http://10.2.177.40:9000/v1/models/deepfm/versions/1:predict -d '
{
"instances":[
{"feat_ids":[7,58,251,....],   //prediction 1
"feat_vals":[1.0,1.0,1.0,...]
},
{"feat_ids":[7,58,251,....],  //prediction 2
"feat_vals":[1.0,1.0,1.0,...]
}
]
}'_ 

i got error message
_{"error": "Model could not be reshaped with requested shape"}_

5. i also tried to  change "shape auto" to "batchsize error", i get this error message 
_{"error": "Error while loading a network"}_

and also this logs
_[modelinstance.cpp:514] exception occurred while loading network: Check 'PartialShape::broadcast_merge_into( pshape, node->get_input_partial_shape(i), autob)' failed at core/src/op/util/elementwise_args.cpp:37:
While validating node 'v1::Multiply Multi-Head-Attention-Layer/multi_head_attention/scale_dot_product_attention/truediv_copy (Multi-Head-Attention-Layer/multi_head_attention/concat_1[0]:f32{8,20,24}, Multi-Head-Attention-Layer/multi_head_attention/scale_dot_product_attention/truediv_copy/const3249965853[0]:f32{4,1,1}) -> (f32{4,20,24})' with friendly_name 'Multi-Head-Attention-Layer/multi_head_attention/scale_dot_product_attention/truediv_copy':
Argument shapes are inconsistent._

so, my question is: how to do batch predictions for any batchsize? which are correct option for mo.py and model server?
thanks !

**Comment by mzegla** [comment]
The log you've posted. Does it appear both with `--shape auto` and `--batch_size auto` with the same message or is it different for each variant?

Also, is it possible that you'd share an XML file of the converted model?

**Comment by yuguanxiang** [comment]
thanks for your reply.
> The log you've posted. Does it appear both with `--shape auto` and `--batch_size auto` with the same message or is it different for each variant?
>
 **Logs are different for the 2 cases
--shape auto  
        >>>{"error": "Model could not be reshaped with requested shape"}
--batch_size auto
        >>>{"error": "Error while loading a network"}****

> Also, is it possible that you'd share an XML file of the converted model?
>
**i change mo.py's input_shape parameter from [1,301],[1,301] => [2,301],[2,301]
python mo.py --log_level=DEBUG --input "feat_ids,feat_vals" --input_shape "[1,301],[1,301]" --saved_model_dir /tmp/1647427562/ --output_dir /tmp/1647427562out
==>
python mo.py --log_level=DEBUG --input "feat_ids,feat_vals" --input_shape "[2,301],[2,301]" --saved_model_dir /tmp/1647427562/ --output_dir /tmp/1647427562out

model server only accept batchsize=2 requests, it reports error when i send a request with batchsize=1,so it seems it only acccept some fixed batch size, 
mo.py doesnt support shape of -1,?,***
do we have some way to support any size batchsize? 
thanks

**Comment by mzegla** [comment]
> Logs are different for the 2 cases
--shape auto
{"error": "Model could not be reshaped with requested shape"}
--batch_size auto
{"error": "Error while loading a network"}**

You also posted a bigger log with more details about the cause of the error. Did you observe it with `--shape` or `--batch_size` parameter?

 

> model server only accept batchsize=2 requests, it reports error when i send a request with batchsize=1,so it seems it only acccept some fixed batch size,
mo.py doesnt support shape of -1,?,***
do we have some way to support any size batchsize?
thanks

So, using `--shape auto` or `--batch_size` auto is one way. It makes model server reload the model to match new input. For some topologies there are issues with propagating input change in later layers - https://docs.openvino.ai/latest/openvino_docs_IE_DG_ShapeInference.html#troubleshooting-reshape-errors.

The other way is to create a pipeline with demultiplexer that will take input with any batch, split it and run inference in parallel on each element separately and then gather the results in the response - https://docs.openvino.ai/latest/ovms_docs_dynamic_bs_demultiplexer.html#doxid-ovms-docs-dynamic-bs-demultiplexer.

You can check out the whole [Dynamic Input Parameters section](https://docs.openvino.ai/latest/ovms_docs_dynamic_input.html) in the documentation for all options to use OVMS with dynamic inputs.

**Comment by yuguanxiang** [comment]
> > Logs are different for the 2 cases
> > --shape auto
> > {"error": "Model could not be reshaped with requested shape"}
> > --batch_size auto
> > {"error": "Error while loading a network"}**
> 
> You also posted a bigger log with more details about the cause of the error. Did you observe it with `--shape` or `--batch_size` parameter?
**it's observed when batch_size parameter is tried**
> > model server only accept batchsize=2 requests, it reports error when i send a request with batchsize=1,so it seems it only acccept some fixed batch size,
> > mo.py doesnt support shape of -1,?,***
> > do we have some way to support any size batchsize?
> > thanks
> 
> So, using `--shape auto` or `--batch_size` auto is one way. It makes model server reload the model to match new input. For some topologies there are issues with propagating input change in later layers - https://docs.openvino.ai/latest/openvino_docs_IE_DG_ShapeInference.html#troubleshooting-reshape-errors.
> 
> The other way is to create a pipeline with demultiplexer that will take input with any batch, split it and run inference in parallel on each element separately and then gather the results in the response - https://docs.openvino.ai/latest/ovms_docs_dynamic_bs_demultiplexer.html#doxid-ovms-docs-dynamic-bs-demultiplexer.
> 
> You can check out the whole [Dynamic Input Parameters section](https://docs.openvino.ai/latest/ovms_docs_dynamic_input.html) in the documentation for all options to use OVMS with dynamic inputs.

thanks for your infomation
i've tried `--shape auto` and `--batch_size`, but it failed to reload the model network
about create a pipeline with demultiplexer , i will study it , looks a bit complicated.

i heard we will have `auto batching` feature for `version 2022.1`, so when will the version be released? 
thanks

**Comment by mzegla** [comment]
That's right, 2022.1 comes with dynamic inputs on OpenVINO side (you will be able to specify shape like [-1, 301])
It should be available in a few days.

**Comment by yuguanxiang** [comment]
> That's right, 2022.1 comes with dynamic inputs on OpenVINO side (you will be able to specify shape like [-1, 301]) It should be available in a few days.

thanks, i will try it in 2022.1
