### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by spradeep28** [openvinotoolkit/model_server#1216]
Broken link in "https://github.com/openvinotoolkit/model_server/blob/main/docs/performance_tuning.md"

[supported configuration parameters for all plugins](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_Supported_Devices.html)

**Comment by rasapala** [comment]
Thank you for the input. The documentation will be fixed in the upcoming release.
