### ISSUE TITLE
OVMS performance in CPU

### ISSUE THREAD

**Issue by m-bulbul** [openvinotoolkit/model_server#1267]
I have a setup where I am serving 5 models and number of requests per second is quite high. 

Here are few things I am trying to understand. 

>As explained in the [throughput-related section](https://docs.openvino.ai/latest/openvino_docs_deployment_optimization_guide_tput.html#doxid-openvino-docs-deployment-optimization-guide-tput), the OpenVINO streams is a mean of running multiple requests in parallel. In order to best serve multiple inference requests executed simultaneously, the inference threads are grouped/pinned to the particular CPU cores, constituting the “CPU” streams. This provides much better performance for the networks than batching especially for the many-core machines:

* **Is inference thread is different from threading in general concept of programming?**
* **For setting optimal CPU_THROUGHPUT_STREAMS , can total number of streams from all model be larger than number NO_CPU_CORE?  (For example CPU_THROUGHPUT_STREAMS for all models has been set to NO_CPU_CORE)**

**Comment by dtrawins** [comment]
@m-bulbul  The concept of inference threads is the same. Inference execution initiates multiple threads to take advantage of execution concurrency and multi core CPUs. By default, OpenVINO is consuming all the cores with the same number of threads.
Some models, however, can not efficiently utilized all cores while some branches of the model topology are executed in sequences. That is observed especially on HW with very high number of cores. STREAMS address this challenge by executing multiple inference requests in parallel. Each stream is using a part of the overall capacity which makes the concurrency more efficient. Increasing the number of streams often improves the throughput when there are multiple inference executions in parallel. It is not recommended to set the number of streams higher from the number of cores. The optimal number of streams might depend on the model, HW capacity, expected latency and the number of parallel inference requests. It is possible to use also a simplified approach with setting just the PERFORMANCE_HINT parameter to LATENCY or THROUGHPUT. You can learn more about the performance aspect of streams on https://github.com/openvinotoolkit/model_server/blob/main/docs/python-benchmarking-client-16feb.pdf

**Comment by m-bulbul** [comment]
Thanks for the input. That helped.

**Comment by m-bulbul** [comment]
Hi @dtrawins, 
I have few more questions,
Here is my understanding, 
* LATENCY mode is preferred for single inference and in LATENCY mode **all the core and threads** are used for the inference. 
* Cores are evenly distributed among STREAMS, so when CPU_THROUGHPUT_STREAMS is set 1, it should perform similar to LATENCY mode for a single model. 

Now for multiple models (say two), since two different model often has different architecture and will take different time for inference how to distribute core accordingly? (say model A 60%, model B 40%) Can we achieve something like this in ovms? (I'm guessing it's through **CPU_THREADS_NUM** ) 

In THROUGHPUT mode, ovms dynamically divides the resources based on the available resources, is it possible to know how many streams each models have been assigned?

**Comment by dtrawins** [comment]
@m-bulbul your understanding for LATENCY mode is correct. It has similar behavior like a single stream.
CPU_THREADS_NUM can limit the number of cores to be consumed by a single model. That way you could reserve certain resources for the model. In can each model is used sporadically it will be still ok to assign all resources for each model. They can be used concurrently using the same resources. Limiting the threads might be recommended if you need to guarantee the response time regardless of the load on the other model.
OVMS is reporting in the logs the number of inference requests creating while loading the model. When --nireq parameter is not set, the number of inference requests in the logs is equal to the number of streams.
