### ISSUE TITLE
Docker image too heavy

### ISSUE THREAD

**Issue by DYSpider13** [openvinotoolkit/model_server#1425]
I'm trying to build an image of the Python real-time-stream-analysis, and since it's using Ubuntu, the image ends up too heavy (more than 1Gb). Is there a specific reason to use Ubuntu, if not is it possible with another image smaller ?

**Comment by mzegla** [comment]
Thank you for bringing this to our attention. It seems that OpenCV installation with APT makes the image 1.8 GB large. 
We'll try to make it smaller and get back to you with suggestions/fixes.

**Comment by mzegla** [comment]
The PR with shrinking the image - https://github.com/openvinotoolkit/model_server/pull/1459
