### ISSUE TITLE
Helm deployment instructions

### ISSUE THREAD

**Issue by ngaloppo** [openvinotoolkit/model_server#1460]
Is the gsutil command in [line 37](https://github.com/openvinotoolkit/model_server/blob/main/deploy/README.md?plain=1#L37) of the README correct? Perhaps the `resnet50-binary-0001.bin` argument is not needed?

```
gsutil cp -r 1 resnet50-binary-0001.bin gs://model-repository/resnet
```

Should the GS path in the line above (`resnet`) the README match the one used in the [single-model deployment example](https://github.com/openvinotoolkit/model_server/blob/main/deploy/README.md#deploy-openvino-model-server-with-a-single-model)? 

```
helm install ovms-app ovms --set model_name=resnet50-binary-0001,model_path=gs://models-repository
```

**Comment by mzegla** [comment]
Seems like these instructions are outdated. We'll fix that some time soon. 
For now please try the guide in OpenVINO Operator repository: https://github.com/openvinotoolkit/operator/blob/main/helm-charts/ovms/README.md#openvino-model-server-deployment-via-a-helm-chart

**Comment by atobiszei** [comment]
Marked as deprecated in model_server repository.
