### ISSUE TITLE
How to speed up the startup time of model_server?

### ISSUE THREAD

**Issue by linchpinlin** [openvinotoolkit/model_server#1532]
Starting the service now takes at least 2.5 seconds(base on bert).
Is there any way to optimize the startup time, hopefully within 1 second? If the startup time is less than 1 second, it is possible to provide tremendous throughput by cloud serverless architecture.
![image](https://user-images.githubusercontent.com/31131753/202668697-6db741b0-fe6e-4c77-b66a-79456799e9a2.png)

**Comment by dkalinowski** [comment]
@linchpinlin 
Logs show that we spend ~4.6s retrieving available device list, ~6.4s loading the model and ~1.6 loading the weights (total 12.6s). Can you explain which part you would like to optimize (refering to the 2.5s from your question).
Is it possible for you to provide the bert model for further investigations?

On the side note, I suggest to use latest OVMS image with latest OpenVINO (2022.2) - you are currently using 2022.1.0.643.

**Comment by linchpinlin** [comment]
Hi [dkalinowski](https://github.com/dkalinowski),

Thank you for your reply.
I want to optimize the process of retrieving the list of available devices and loading the model. 
Our production environment was updated to OpenVINO (2022.2). The startup time of the bert model varies from 660ms to 16s, which is very confusing. 
According to [the model caching documentation](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Model_caching_overview.html), the startup time is fixed at around 1 second.

**Comment by dkalinowski** [comment]
@linchpinlin 
Few more questions:
- which hardware are you trying to load the model into? cpu/vpu/gpu? which version?
- regarding the BERT model you use, is it similar to this BERT https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/bert-large-uncased-whole-word-masking-squad-int8-0001 ? Or is it possible for you to provide the model (even the untrained one would be good)
- please provide entire docker run command (or are you using ovms operator? if so, please specify the startup environment - with config.json if used)
- please provide complete logs with debug level (run with `--log_level DEBUG` param)

**Comment by linchpinlin** [comment]
@dkalinowski 
We are running pod on self-hosted K8S, when we upgrade HDD to SSD, this problem is solved.
Thank you for your help.

- Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz (pod cpu limit: 4)
- https://open.zhuiyi.ai/releases/nlp/models/zhuiyi/chinese_simbert_L-12_H-768_A-12.zip
- Docker file : ENTRYPOINT /ovms/bin/ovms --model_path /models/simbert-base-chinese-openvino --model_name simbert-base-chinese-openvino --port 8500
