### ISSUE TITLE
Cannot create reorder primitive: unsupported reorder case

### ISSUE THREAD

**Issue by MohamedDonia** [openvinotoolkit/model_server#1591]
Hello
Iam trying to infer crnn model using ovms2022.2 but gets this error 
`
[modelmanager][error][modelinstance.cpp:671] Cannot compile model into target device; error: Cannot create reorder primitive: unsupported reorder case; model: euler; version: 1; device: CPU
`
despite this model is working on ovms2021.4 and ovms2020

**Comment by dtrawins** [comment]
@MohamedDonia can you share the model or point to some public model with similar topology and symptoms? 
Can you try if using the model optimizer 2022.2 or 2022.3 resolves that issue?
What parameters are you using to start ovms server?

**Comment by atobiszei** [comment]
Will close the issue within week if we get no response.
