### ISSUE TITLE
different output ovms 2021.4 and 20214.2

### ISSUE THREAD

**Issue by MohamedDonia** [openvinotoolkit/model_server#1594]
I am trying to infer crnn model using open vino mode server 2021.4 and 2021.4.2 and they gets different  output
both models have the same IR representation converted using **openvino_2021.4.752** 
the correct output is the one with ovms 2021.4

**Comment by atobiszei** [comment]
Hi @MohamedDonia 
Did you try to load this model with pure OV 2021.4 and 2021.4.2?
Could you provide debug logs? (--log_level DEBUG)
Could you provide the model?

**Comment by atobiszei** [comment]
Will close the issue within week if we get no response.
