### ISSUE TITLE
Version: no such file or directory

### ISSUE THREAD

**Issue by sokol88-dap** [openvinotoolkit/model_server#166]
When I build dockerfile from master branch the builder returned follows error:

Step 12/15 : RUN virtualenv -p python3 .venv &&     . .venv/bin/activate && pip3 --no-cache-dir install -r requirements.txt
 ---> Using cache
 ---> a02618f3f829
Step 13/15 : COPY start_server.sh setup.py version /ie-serving-py/
COPY failed: stat /var/lib/docker/tmp/docker-builder232822774/version: no such file or directory

If remove the version file from line
COPY start_server.sh setup.py version /ie-serving-py/
then build is done successfully

**Comment by mzegla** [comment]
You're right. Our Dockerfiles rely on a `version` file generated when building with `make`. 
e.g. https://github.com/IntelAI/OpenVINO-model-server/blob/master/Makefile#L92
So building directly with `docker build` will fail if you don't have this `version` file. 

Thank you for pointing that out. We'll try to get rid of this dependency.

**Comment by rasapala** [comment]
Issue resolved. No version file needed in OVMS 2021.1. Recommended using `make docker_build`
