### ISSUE TITLE
Publish image in alternate registry

### ISSUE THREAD

**Issue by anishasthana** [openvinotoolkit/model_server#1676]
Hi folks,

Have you considered publishing your images in a location such as Quay or Gcr? DockerHub ends up resulting in pull rate back offs quite frequently.

**Comment by dkalinowski** [comment]
Hello @anishasthana 
We also publish the image to redhat registry: https://catalog.redhat.com/software/containers/intel/openvino-model-server/607833052937385fc98515de

**Comment by atobiszei** [comment]
If there is no response, the topic will be closed within a week.

**Comment by anishasthana** [comment]
Apologies, I meant to reply. Thanks @dkalinowski! We can close this out.
