### ISSUE TITLE
When will it support kaldi model? Many thanks.

### ISSUE THREAD

**Issue by jiaymjiaym** [openvinotoolkit/model_server#170]

**Comment by brmarkus** [comment]
Once the files are converted (see e.g. "https://docs.openvinotoolkit.org/latest/_inference_engine_samples_speech_sample_README.html") they can be used.

**Comment by jiaymjiaym** [comment]
> Once the files are converted (see e.g. "https://docs.openvinotoolkit.org/latest/_inference_engine_samples_speech_sample_README.html") they can be used.

Hi, brmarkus. Thank you very much. You mean If I convert the kaldi model to openvino format, I can also use the model server in K8S, just the same as other model such as tensorflow model?

**Comment by brmarkus** [comment]
I haven't tried converted Kaldi models to be honest, but yes, models in OpenVINO's IR format can be used.

**Comment by jiaymjiaym** [comment]
> I haven't tried converted Kaldi models to be honest, but yes, models in OpenVINO's IR format can be used.
> The speech sample "Automatic Speech Recognition" looks a bit more complicated than other samples in terms of parameters and steps to provide the data for doing inference...

In fact, I have tested the “Automatic Speech Recognition” in openvino toolkit.  I want to integrate it to openvino model server for easier CI/CD.  I will give a try. Thank you.

**Comment by rasapala** [comment]
@jiaymjiaym Please let us know if you need more help.

**Comment by rasapala** [comment]
No more help needed.
