### ISSUE TITLE
GPT-J Causal Language Modeling Demo problem

### ISSUE THREAD

**Issue by silvacarl2** [openvinotoolkit/model_server#1741]
python download_model.py - works great!
./convert_model.sh - works great!
docker run -d --rm -p 9000:9000 -v $(pwd)/onnx:/model:ro openvino/model_server \
    --port 9000 \
    --model_name gpt-j-6b \
    --model_path /model \
    --plugin_config '{"PERFORMANCE_HINT":"LATENCY","NUM_STREAMS":1}' - doesnt work no matter what I do.

it says it cannot find the model, any ideas?

**Comment by atobiszei** [comment]
Could you please share the logs?

**Comment by atobiszei** [comment]
Closed due to no response.
