### ISSUE TITLE
[Question] Model Quantization

### ISSUE THREAD

**Issue by Taicun-iEi** [openvinotoolkit/model_server#1982]
Just a question, not sure asking on here is available or not.     
   
I'm try to follow quick start to setup ovms.    
And try to validate FP32/FP16/INT8 model, but only FP32 input work for it.    
   
output log   
```
Model:face-detection-retail-0004/FP32
Expected: FP32; Actual: FP32; Status:SUCCESS

Expected: FP32; Actual: FP16; Status:INVALID
        status = StatusCode.INVALID_ARGUMENT
        details = "Invalid input precision - Expected: FP32; Actual: FP16; input name: data"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:9000 {grpc_message:"Invalid input precision - Expected: FP32; Actual: FP16; input name: data", grpc_status:3, created_time:"2023-08-09T15:39:24.573639117+08:00"}"
        
Expected: FP32; Actual: U8; Status:INVALID
        status = StatusCode.INVALID_ARGUMENT
        details = "Invalid input precision - Expected: FP32; Actual: U8; input name: data"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:9000 {grpc_message:"Invalid input precision - Expected: FP32; Actual: U8; input name: data", grpc_status:3, created_time:"2023-08-09T15:37:30.500837486+08:00"}"



Model:face-detection-retail-0004/FP16
Expected: FP32; Actual: FP32; Status:SUCCESS

Expected: FP32; Actual: FP16; Status:INVALID
        status = StatusCode.INVALID_ARGUMENT
        details = "Invalid input precision - Expected: FP32; Actual: FP16; input name: data"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:9000 {created_time:"2023-08-09T15:50:54.451550115+08:00", grpc_status:3, grpc_message:"Invalid input precision - Expected: FP32; Actual: FP16; input name: data"}"
        
Expected: FP32; Actual: U8; Status:INVALID
        status = StatusCode.INVALID_ARGUMENT
        details = "Invalid input precision - Expected: FP32; Actual: U8; input name: data"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:9000 {grpc_message:"Invalid input precision - Expected: FP32; Actual: U8; input name: data", grpc_status:3, created_time:"2023-08-09T15:52:02.841669499+08:00"}"


Model:face-detection-retail-0004/FP16-INT8
Expected: FP32; Actual: FP32; Status:SUCCESS

Expected: FP32; Actual: FP16; Status:INVALID
        status = StatusCode.INVALID_ARGUMENT
        details = "Invalid input precision - Expected: FP32; Actual: FP16; input name: data"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:9000 {created_time:"2023-08-09T15:54:47.351255173+08:00", grpc_status:3, grpc_message:"Invalid input precision - Expected: FP32; Actual: FP16; input name: data"}"
        
Expected: FP32; Actual: U8; Status:INVALID
        status = StatusCode.INVALID_ARGUMENT
        details = "Invalid input precision - Expected: FP32; Actual: U8; input name: data"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:9000 {grpc_message:"Invalid input precision - Expected: FP32; Actual: U8; input name: data", grpc_status:3, created_time:"2023-08-09T15:54:07.467204758+08:00"}"
```   
     
detail validate step screenshot   
   
- Model:face-detection-retail-0004/FP32    
default model is fp32    
Expected: FP32; Actual: FP32; Status:SUCCESS
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/aaed482a-dd15-4e0b-a56c-dbda4eabfe72)
Expected: FP32; Actual: FP16; Status:INVALID
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/18e443f1-8399-4b3e-aa45-a522508d6100)
Expected: FP32; Actual: U8; Status:INVALID
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/ca5a15f4-8bdf-4e30-9a8b-4aa2deeb244f)
    
- Model:face-detection-retail-0004/FP16   
change model to fp16   
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/f8de9528-96d0-4138-a7d8-de060a93b936)
Expected: FP32; Actual: FP32; Status:SUCCESS
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/de344392-ee12-4dc9-87f2-c37ca710b4ec)
Expected: FP32; Actual: FP16; Status:INVALID
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/40002517-9f54-464d-b312-c9aa3ffc001d)
Expected: FP32; Actual: U8; Status:INVALID
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/2c79fde8-7654-4237-bcff-94bfa10cd6dd)
    
- Model:face-detection-retail-0004/FP16-INT8   
change model to int8   
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/87f85986-4c23-4d34-af5d-c326a3420744)
Expected: FP32; Actual: FP32; Status:SUCCESS
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/0b4cf759-5d7e-4280-83de-38061af9067f)
Expected: FP32; Actual: FP16; Status:INVALID
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/f0572f98-9c70-4644-bd06-0f76c8a7ecdc)
Expected: FP32; Actual: U8; Status:INVALID
![image](https://github.com/openvinotoolkit/model_server/assets/134986506/119006be-c571-4aae-a9c0-dfa5e2f35726)
      
my sample code   
```python
import cv2
import datetime
import grpc
import numpy as np
import os

from tensorflow import make_tensor_proto, make_ndarray
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc

address = "localhost:9000"
width = 600
height = 400
path = "./images/people1.jpeg"
batch_size = 1
model_name ="face-detection"
output_dir ="./results"

img = cv2.imread(path) 
img = cv2.resize(img, (width, height))
img = img.transpose(2,0,1).reshape(1,3,height,width)
img = img.astype(np.float32)

channel = grpc.insecure_channel(address)
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)
request = predict_pb2.PredictRequest()
request.model_spec.name = model_name
request.inputs["data"].CopyFrom(make_tensor_proto(img, shape=(img.shape)))
result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs

output = make_ndarray(result.outputs["detection_out"])
for y in range(0,img.shape[0]):
    img_out = img[y,:,:,:]
    img_out = img_out.transpose(1,2,0)
    for i in range(0, 200*batch_size-1): 
        detection = output[:,:,i,:]
        if detection[0,0,2] > 0.5 and int(detection[0,0,0]) == y:  
            x_min = int(detection[0,0,3] * width)
            y_min = int(detection[0,0,4] * height)
            x_max = int(detection[0,0,5] * width)
            y_max = int(detection[0,0,6] * height)
            img_out = cv2.rectangle(cv2.UMat(img_out),(x_min,y_min),(x_max,y_max),(0,0,255),1)

    cv2.imwrite("./output.jpg",img_out)
```

**Comment by dtrawins** [comment]
@Taicun-iEi 
When you perform the model quantization, the internal hidden layers are updated to use lower precision. The input and output tensors are preserved so there is still expected input precision like in the original model. So the client should still send the data in FP32 precision but the performance should be better.
It is possible to change the precision of the input and output using the model optimizer. You would need to make sure the range of the expected input fits to the new precision value. For example, when the model uses float input in the rage of 0-1, changing it to int8 will not give good results.

**Comment by Taicun-iEi** [comment]
got it, thanks you so much!!!!
