### ISSUE TITLE
use ovms_ubuntu20 c-api link failed

### ISSUE THREAD

**Issue by liyandong001** [openvinotoolkit/model_server#2031]
![image](https://github.com/openvinotoolkit/model_server/assets/114555621/c329b7be-9c2c-4280-a034-541adfe1bab7)
![image](https://github.com/openvinotoolkit/model_server/assets/114555621/afa40f0c-07dc-4445-92b8-48e533eacb5f)

**Comment by atobiszei** [comment]
Please make sure that you use ovms shared library build from main. In this release we change API from 0.3 to 1.0 and there are minor naming changes. In this case removing "*Get*" from API function.

**Comment by atobiszei** [comment]
OVMS 2023.1 was recently released - please check if with newest binaries:
https://github.com/openvinotoolkit/model_server/releases/tag/v2023.1

**Comment by atobiszei** [comment]
To be closed in 1 week when no response
