### ISSUE TITLE
Performance benchmarking using OVMS

### ISSUE THREAD

**Issue by jerin-scalers-ai** [openvinotoolkit/model_server#2064]
I looking at the [OpenVINO performance benchmark](https://docs.openvino.ai/2023.1/openvino_docs_performance_benchmarks.html#) for YOLO v8 model using OVMS benchmark setup.
How to reproduce the YOLOv8 results using OVMS benchmark setup shown in methodology section.

**Comment by kpapis** [comment]
Hi @jerin-scalers-ai, for performance measurements you can use [Benchmark Client](https://github.com/openvinotoolkit/model_server/tree/main/demos/benchmark/python). Under the link you will find deployment steps and usage examples, which can be adapted to your specific case.

**Comment by jerin-scalers-ai** [comment]
Hi @kpapis ,
Thanks for pointing out the benchmark client. 
Is the becnchmark client implementation is same as the architecture in this [page](https://docs.openvino.ai/2023.1/openvino_docs_performance_benchmarks.html#platforms-configurations-methodology) with gRPC client, controller, HAProxy  etc  ?

**Comment by kpapis** [comment]
Hi @jerin-scalers-ai, yes, the same architecture of Benchmark Client was used for benchmarks shown in [docs](https://docs.openvino.ai/2023.1/openvino_docs_performance_benchmarks.html#platforms-configurations-methodology).
