### ISSUE TITLE
Serving bigcode StarCoderBase model in model server.

### ISSUE THREAD

**Issue by BalajiAJ** [openvinotoolkit/model_server#2080]
We are trying to host starcoderbase-3B parameter model in OVMS, but running into multiple errors. Are there any reference documentation available for hosting bigcode based models? Thanks!

**Comment by atobiszei** [comment]
Hi @BalajiAJ,
could you please share logs from OVMS?

**Comment by atobiszei** [comment]
Closed due to no response. Please reopen if needed.
