### ISSUE TITLE
Can a single server instance use multiple NCS devices?

### ISSUE THREAD

**Issue by dcflachs** [openvinotoolkit/model_server#216]
Will a single server instance utilize multiple NCS devices to accelerate a single model?

**Comment by mzegla** [comment]
@mateusz-ciesielski Could multi device plugin be a solution here?

**Comment by dcflachs** [comment]
@mzegla Thanks, you comment led me to the answer to my question. Buried in the [documentation](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_MULTI.html ) for the MULTI device plugin it describes how to list multiple MYRIAD devices and then use them as part of the multi plugin. 
`"MULTI:MYRIAD.1.2-ma2480,MYRIAD.1.4-ma2480"`
