### ISSUE TITLE
Dockerfile build unsuccessful

### ISSUE THREAD

**Issue by stevegrubb** [openvinotoolkit/model_server#2391]
When performing a Dockerfile.redhat build with podman, the build eventually terminates in the SENTENCEPIECE_EXTENSION. It mentions a warning like this:

  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

Is tbb required for this section of the build? If so, adding: ENV TBB_DIR=/openvino/cmake/developer_package/tbb/lnx/ and adding this package to yum install https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/tbb-devel-2018.2-9.el8.x86_64.rpm gets rid of the warning.

However, this is just a warning. The failure is this

  List of custom operations in user_ov_extensions extension: 
CMake Error at user_ie_extensions/CMakeLists.txt:74 (message):
  user_ov_extensions does not have operation with name 'tokenizer'

It lists no extensions however the build has -DCUSTOM_OPERATIONS="tokenizer". Looking into this, I found https://github.com/openvinotoolkit/openvino_contrib/pull/887 which removes the tokenizer. Is the tokenizer needed? If so, how would it be added to the build?

To reproduce, clone the main branch on a Fedora/RHEL machine. Do a podman build using the Dockerfile.redhat and wait.

**Comment by dkalinowski** [comment]
@stevegrubb Yes, OpenVINO has moved custom tokenizer layers to separate repo. We have integrated this change to main branch yesterday: https://github.com/openvinotoolkit/model_server/commit/f76dedc96b3c48d9e030ad2836db189842b01fc2
Please check with the latest main branch commit.

**Comment by stevegrubb** [comment]
Thanks! Looks like it now gets past the tokenizer issue. Now it's dying at:

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/b9d4073a6913891ce9cbd8965c8d506075d2a45a.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: /ovms/src/BUILD:69:18: in cc_shared_library rule

Wonder if the archive moved or got deleted? Visiting https://storage.googleapis.com/mirror.tensorflow.org/ shows that there are more XNNPACK zip files. Just not the one the build script is looking for.

**Comment by dkalinowski** [comment]
Should be temporary hiccup for google mirrors. Can you rebuild? @stevegrubb

**Comment by stevegrubb** [comment]
I did a rebuild using the repo as it was when it failed last week. It still fails at the same point. Then I did a git pull to update the repo to what is current this morning.  The build still fails at the same point. 

I don't know how it chooses the b9d4073...zip file. But looking at where it's pulling from, there are 48 more XNNPACK copies it can select from. The one it wants just isn't there.

**Comment by atobiszei** [comment]
@stevegrubb Could you please post full build command and wider context from logs around line this:
ERROR: /ovms/src/BUILD:69:18: in cc_shared_library rule?

**Comment by stevegrubb** [comment]
The build command is:

podman build --tag my:model_server --build-arg RUN_TESTS=0  --build-arg BUILDAH_FORMAT=docker --build-arg ov_use_binary=0 --build-arg BASE_OS=redhat --build-arg RH_ENTITLEMENT=0  -f Dockerfile.redhat

I can post more in a little while. But it boils down to the file it selects for XNNPACK is not there:

# wget https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/b9d4073a6913891ce9cbd8965c8d506075d2a45a.zip
--2024-04-11 08:26:15--  https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/b9d4073a6913891ce9cbd8965c8d506075d2a45a.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.64.219, 142.250.217.187, 142.250.217.219, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.64.219|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-11 08:26:16 ERROR 404: Not Found.

**Comment by stevegrubb** [comment]
Here's a little more of the logs:

[2/4] STEP 88/103: ARG CAPI_FLAGS=--strip=always --define MEDIAPIPE_DISABLE=1 --cxxopt=-DMEDIAPIPE_DISABLE=1 --define PYTHON_DISABLE=1 --cxxopt=-DPYTHON_DISABLE=1
WARN[1915] SHELL is not supported for OCI image format, [/bin/bash -xo pipefail -c] will be ignored. Must use `docker` format 
--> c4b42aa55a1c
[2/4] STEP 89/103: RUN bazel build --jobs $JOBS ${CAPI_FLAGS} //src:ovms_shared
Starting local Bazel server and connecting to it...
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/rules_python/python/repositories.bzl:32:10: py_repositories is a no-op and is deprecated. You can remove this from your WORKSPACE file
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'icu' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'boringssl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
Loading: 
Loading: 0 packages loaded
Analyzing: target //src:ovms_shared (1 packages loaded, 0 targets configured)
Analyzing: target //src:ovms_shared (210 packages loaded, 5992 targets configured)
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/tensorflow_serving/tensorflow_serving/config/BUILD:36:22: in cc_library rule @tensorflow_serving//tensorflow_serving/config:model_server_config_proto: target '@tensorflow_serving//tensorflow_serving/config:model_server_config_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule @mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/mediapipe/mediapipe/framework/BUILD:59:24: in cc_library rule @mediapipe//mediapipe/framework:calculator_cc_proto: target '@mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/tensorflow_serving/tensorflow_serving/apis/BUILD:84:22: in cc_library rule @tensorflow_serving//tensorflow_serving/apis:model_proto: target '@tensorflow_serving//tensorflow_serving/apis:model_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/tensorflow_serving/tensorflow_serving/apis/BUILD:24:22: in cc_library rule @tensorflow_serving//tensorflow_serving/apis:get_model_metadata_proto: target '@tensorflow_serving//tensorflow_serving/apis:get_model_metadata_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
DEBUG: Rule 'nlohmann_json' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03", shallow_since = "1701207391 +0100" and dropping ["tag"]
DEBUG: Repository nlohmann_json instantiated at:
  /ovms/WORKSPACE:424:15: in <toplevel>
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/bazel_tools/tools/build_defs/repo/git.bzl:176:33: in <toplevel>
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/tensorflow/core/BUILD:264:11: in hdrs attribute of cc_library rule @org_tensorflow//tensorflow/core:lib: Artifact 'external/org_tensorflow/tensorflow/tsl/platform/abi.h' is duplicated (through '@org_tensorflow//tensorflow/core/platform:lib_hdrs' and '@org_tensorflow//tensorflow/tsl/platform:lib_hdrs')
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/tensorflow/core/BUILD:264:11: in hdrs attribute of cc_library rule @org_tensorflow//tensorflow/core:lib: Artifact 'external/org_tensorflow/tensorflow/tsl/platform/bfloat16.h' is duplicated (through '@org_tensorflow//tensorflow/core/platform:lib_hdrs' and '@org_tensorflow//tensorflow/tsl/platform:lib_hdrs')

a little later

WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/tensorflow/core/BUILD:264:11: in hdrs attribute of cc_library rule @org_tensorflow//tensorflow/core:lib: Artifact 'external/org_tensorflow/tensorflow/tsl/platform/profile_utils/android_armv7a_cpu_utils_helper.h' is duplicated (through '@org_tensorflow//tensorflow/core/platform:lib_hdrs' and '@org_tensorflow//tensorflow/tsl/platform:lib_hdrs')
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/tensorflow/core/BUILD:264:11: in hdrs attribute of cc_library rule @org_tensorflow//tensorflow/core:lib: Artifact 'external/org_tensorflow/tensorflow/tsl/platform/profile_utils/clock_cycle_profiler.h' is duplicated (through '@org_tensorflow//tensorflow/core/platform:lib_hdrs' and '@org_tensorflow//tensorflow/tsl/platform:lib_hdrs')
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/tensorflow/core/BUILD:264:11: in hdrs attribute of cc_library rule @org_tensorflow//tensorflow/core:lib: Artifact 'external/org_tensorflow/tensorflow/tsl/platform/profile_utils/cpu_utils.h' is duplicated (through '@org_tensorflow//tensorflow/core/platform:lib_hdrs' and '@org_tensorflow//tensorflow/tsl/platform:lib_hdrs')
WARNING: /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/org_tensorflow/tensorflow/core/BUILD:264:11: in hdrs attribute of cc_library rule @org_tensorflow//tensorflow/core:lib: Artifact 'external/org_tensorflow/tensorflow/tsl/platform/profile_utils/i_cpu_utils_helper.h' is duplicated (through '@org_tensorflow//tensorflow/core/platform:lib_hdrs' and '@org_tensorflow//tensorflow/tsl/platform:lib_hdrs')
Analyzing: target //src:ovms_shared (281 packages loaded, 19445 targets configured)
Analyzing: target //src:ovms_shared (305 packages loaded, 20786 targets configured)
Analyzing: target //src:ovms_shared (305 packages loaded, 159713 targets configured)
Analyzing: target //src:ovms_shared (305 packages loaded, 159719 targets configured)
Analyzing: target //src:ovms_shared (305 packages loaded, 159719 targets configured)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/b9d4073a6913891ce9cbd8965c8d506075d2a45a.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: target //src:ovms_shared (307 packages loaded, 160725 targets configured)
ERROR: /ovms/src/BUILD:69:18: in cc_shared_library rule //src:ovms_shared: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 453, column 105, in _cc_shared_library_impl
	File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 349, column 37, in _filter_inputs
	File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 386, column 9, in _throw_error_if_unaccounted_libs
Error in fail: The following libraries cannot be linked either statically or dynamically:
@nlohmann_json//:json
To ignore which libraries get linked statically for now, add the following to 'static_deps':
        "@nlohmann_json//:__subpackages__",
ERROR: /ovms/src/BUILD:69:18: Analysis of target '//src:ovms_shared' failed
ERROR: Analysis of target '//src:ovms_shared' failed; build aborted: 
INFO: Elapsed time: 10.436s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (307 packages loaded, 160725 targets configured)
Error: building at STEP "RUN bazel build --jobs $JOBS ${CAPI_FLAGS} //src:ovms_shared": while running runtime: exit status 1

This roughly corresponds to src/BUILD line 106:

cc_shared_library(
    name = "ovms_shared",
    dynamic_deps = [],
    static_deps = ["@tensorflow_serving//:__subpackages__",
...
        "@upb//:__subpackages__",
        "@zlib//:__subpackages__",
        "@com_github_glog_glog//:__subpackages__",
        "@com_github_gflags_gflags//:__subpackages__",
-->   "@XNNPACK//:__subpackages__",
        "@pthreadpool//:__subpackages__",
        "@FXdiv//:__subpackages__",
        "@FP16//:__subpackages__",

**Comment by stevegrubb** [comment]
I updated my repo and reran the build. This is new as it now has DEBUG statements:

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/b9d4073a6913891ce9cbd8965c8d506075d2a45a.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: Rule 'nlohmann_json' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03", shallow_since = "1701207391 +0100" and dropping ["tag"]
DEBUG: Repository nlohmann_json instantiated at:
  /ovms/WORKSPACE:424:15: in <toplevel>
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/external/bazel_tools/tools/build_defs/repo/git.bzl:176:33: in <toplevel>

**Comment by dkalinowski** [comment]
Okay, I have re-created your setup (which is unusual since we always use the `Makefile` instead of manually running docker/podman) and at first glance it looks like mistakes in build arguments:

My command (using docker instead of podman):
```
$ docker build --tag my:model_server --build-arg RUN_TESTS=0 --build-arg ov_use_binary=0 --build-arg BASE_OS=redhat --build-arg RH_ENTITLEMENT=0 -f Dockerfile.redhat .
```

**I'm getting the same XNNPACK 404 errors as you do.**

By analyzing the make file, we can see more parameters being passed to docker build:
```
BUILD_ARGS = --build-arg http_proxy=$(HTTP_PROXY)\
	--build-arg https_proxy=$(HTTPS_PROXY)\
	--build-arg no_proxy=$(NO_PROXY)\
	--build-arg ov_source_branch=$(OV_SOURCE_BRANCH)\
	--build-arg ov_source_org=$(OV_SOURCE_ORG)\
	--build-arg ov_contrib_org=$(OV_CONTRIB_ORG)\
	--build-arg ov_use_binary=$(OV_USE_BINARY)\
	--build-arg tokenizers=$(TOKENIZERS)\
	--build-arg DLDT_PACKAGE_URL=$(DLDT_PACKAGE_URL)\
	--build-arg CHECK_COVERAGE=$(CHECK_COVERAGE)\
	--build-arg RUN_TESTS=$(RUN_TESTS)\
	--build-arg FUZZER_BUILD=$(FUZZER_BUILD)\
	--build-arg debug_bazel_flags=$(BAZEL_DEBUG_FLAGS)\
	--build-arg minitrace_flags=$(MINITRACE_FLAGS) \
	--build-arg CMAKE_BUILD_TYPE=$(CMAKE_BUILD_TYPE)\
	--build-arg PROJECT_VERSION=$(PROJECT_VERSION)\
	--build-arg BASE_IMAGE=$(BASE_IMAGE)\
	--build-arg NVIDIA=$(NVIDIA)\
	--build-arg ov_contrib_branch=$(OV_CONTRIB_BRANCH)\
	--build-arg ov_tokenizers_branch=$(OV_TOKENIZERS_BRANCH)\
	--build-arg INSTALL_RPMS_FROM_URL=$(INSTALL_RPMS_FROM_URL)\
	--build-arg INSTALL_DRIVER_VERSION=$(INSTALL_DRIVER_VERSION)\
	--build-arg GPU=$(GPU)\
	--build-arg RELEASE_BASE_IMAGE=$(BASE_IMAGE_RELEASE)\
	--build-arg JOBS=$(JOBS)\
	--build-arg CAPI_FLAGS=$(CAPI_FLAGS)
```

| Makefile param/Dockerfile param | Makefile default value | Dockerfile default value |
| --- | --- | --- |
| HTTP_PROXY/http_proxy | from env | from default docker config file |
| HTTPS_PROXY/https_proxy | from env  | from default docker config file |
| NO_PROXY/no_proxy | from env | from default docker config file |
| OV_SOURCE_BRANCH/ov_source_branch | c26745a5fcf21b5ea0dc1b1f714c928433217445  | master |
|OV_SOURCE_ORG/ov_source_org | openvinotoolkit | openvinotoolkit |
|OV_CONTRIB_ORG/ov_contrib_org | openvinotoolkit | openvinotoolkit |
|OV_USE_BINARY/ov_use_binary | 0 | 0 |
|TOKENIZERS/tokenizers | 1 | 1 |
|DLDT_PACKAGE_URL/DLDT_PACKAGE_URL | internal link depending on OS | |
|CHECK_COVERAGE/CHECK_COVERAGE | 0 | 0 |
|RUN_TESTS/RUN_TESTS | 1 | 1 |
|FUZZER_BUILD/FUZZER_BUILD | 0 | 0 |
| BAZEL_DEBUG_FLAGS/debug_bazel_flags| --strip=always --define MEDIAPIPE_DISABLE=0 --define PYTHON_DISABLE=0  --//:distro=redhat | --strip=never |
|MINITRACE_FLAGS/minitrace_flags|  | |
|CMAKE_BUILD_TYPE/CMAKE_BUILD_TYPE | Release | Release |
|PROJECT_VERSION/PROJECT_VERSION | from `git rev-parse --short HEAD` | 2024.0  |
| BASE_IMAGE/BASE_IMAGE |  registry.access.redhat.com/ubi8/ubi:8.9| registry.access.redhat.com/ubi8/ubi:8.9 |
| NVIDIA/NVIDIA | 0 | 0 |
| OV_CONTRIB_BRANCH/ov_contrib_branch |8f238178616b47fb11fc3df0df99baf9e0df397d  |  master |
| OV_TOKENIZERS_BRANCH/ov_tokenizers_branch | 01f15a0f3a0b631bdbf2b3b91b8e0b88690545ff | 2024.0.0.0 |
| INSTALL_RPMS_FROM_URL/INSTALL_RPMS_FROM_URL | | |
| INSTALL_DRIVER_VERSION/INSTALL_DRIVER_VERSION | 23.22.26516 | 23.22.26516 |
| GPU/GPU | 0 | 0 |
| BASE_IMAGE_RELEASE/RELEASE_BASE_IMAGE | registry.access.redhat.com/ubi8/ubi-minimal:8.9 | |
| JOBS/JOBS | cores * sockets | 8 |
| CAPI_FLAGS/CAPI_FLAGS|  --strip=always --define MEDIAPIPE_DISABLE=1 --define PYTHON_DISABLE=1  --//:distro=redhat | --strip=always --define MEDIAPIPE_DISABLE=1 --cxxopt=-DMEDIAPIPE_DISABLE=1 --define PYTHON_DISABLE=1 --cxxopt=-DPYTHON_DISABLE=1 |

This command worked for me @stevegrubb (or just use Makefile):
```
$ docker build --tag my:model_server --build-arg RUN_TESTS=0 --build-arg ov_use_binary=0 --build-arg BASE_OS=redhat --build-arg RH_ENTITLEMENT=0 --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg ov_source_branch=c26745a5fcf21b5ea0dc1b1f714c928433217445 --build-arg debug_bazel_flags="--strip=always --define MEDIAPIPE_DISABLE=0 --define PYTHON_DISABLE=0 --//:distro=redhat" --build-arg ov_contrib_branch=8f238178616b47fb11fc3df0df99baf9e0df397d --build-arg ov_tokenizers_branch=01f15a0f3a0b631bdbf2b3b91b8e0b88690545ff --build-arg RELEASE_BASE_IMAGE=registry.access.redhat.com/ubi8/ubi-minimal:8.9 --build-arg CAPI_FLAGS="--strip=always --define MEDIAPIPE_DISABLE=1 --define PYTHON_DISABLE=1 --//:distro=redhat" -f Dockerfile.redhat .
```

**Comment by stevegrubb** [comment]
I can confirm that PR #2414 fixes the build. Thanks!
