### ISSUE TITLE
rag_chatbot demo: client_requirements.txt does not install all packages needed

### ISSUE THREAD

**Issue by EdjeElectronics** [openvinotoolkit/model_server#2456]
**Describe the bug**
I worked through the [rag_chatbot](https://github.com/openvinotoolkit/model_server/tree/main/demos/python_demos/rag_chatbot) demo and was able to get it working successfully with the `tiny-llama-1b-chat`. However, I encountered missing package errors when running the Gradio example (`app.py`). I had to install the `gradio` and `tritonclient[grpc]` packages to get the example to work. 

The instructions in the [Run gradio client with gRPC streaming](https://github.com/openvinotoolkit/model_server/tree/main/demos/python_demos/rag_chatbot#run-gradio-client-with-grpc-streaming) part of the demo should be changed to:

```
pip install -r client_requirements.txt
pip install gradio
pip install tritonclient[grpc]
```

That, or the `client_requirements.txt` file should be changed to have the needed packages added.

**Error Logs**
Here are the error logs from running the example.

```
(rag-env) lappytop-l@lappytop-l-1:~/model_server/demos/python_demos/rag_chatbot$ python app.py --web_url localhost:9001 --ovms_url localhost:9000
Traceback (most recent call last):
  File "/home/lappytop-l/model_server/demos/python_demos/rag_chatbot/app.py", line 17, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```
After I installed `gradio` using `pip install gradio`, I then encountered this error.
```
(rag-env) lappytop-l@lappytop-l-1:~/model_server/demos/python_demos/rag_chatbot$ python app.py --web_url localhost:9001 --ovms_url localhost:9000
Traceback (most recent call last):
  File "/home/lappytop-l/model_server/demos/python_demos/rag_chatbot/app.py", line 20, in <module>
    from streamer import OvmsStreamer
  File "/home/lappytop-l/model_server/demos/python_demos/rag_chatbot/streamer.py", line 17, in <module>
    import tritonclient.grpc as grpcclient
ModuleNotFoundError: No module named 'tritonclient'
```

**To Reproduce**
1. Follow the instructions in the [rag_chatbot](https://github.com/openvinotoolkit/model_server/tree/main/demos/python_demos/rag_chatbot) demo

cc @ryanloney

**Comment by atobiszei** [comment]
Hi @EdjeElectronics,
what python version are you using? Is python2 installed there?

Client requirements are in place:
https://github.com/openvinotoolkit/model_server/blob/v2024.1/demos/python_demos/rag_chatbot/client_requirements.txt
and there is tritonclient & gradio.

Could you check if pip installed packages for the python version that you are using?
