### ISSUE TITLE
[FEAT] Add "Usage" field to Non-streaming OpenAI-API-Compatible LLM Response

### ISSUE THREAD

**Issue by tjtanaa** [openvinotoolkit/model_server#2626]
Will there be plans to complete the support of OpenAI-API-Compatible Endpoints?
There are many existing LLM libraries and application would depend on the "Usage" field of the response when the `stream` argument is set to false.

Currently the following are the response model from the chat-completion endpoint:

```
{
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "message": {
        "content": "OpenVINO is an open-source project developed by Microsoft. It's designed to help users develop, train, and deploy deep learning models",
        "role": "assistant"
      }
    }
  ],
  "created": 1723712912,
  "model": "microsoft/Phi-3-mini-128k-instruct",
  "object": "chat.completion"
}
```

**Comment by mzegla** [comment]
Yes, we plan to gradually increase API support for OpenAI endpoints in the future. 
As for `usage`, it is planned for the next release.

**Comment by mzegla** [comment]
Support for `usage` has been merged to main branch. You can use it now if you build the docker image (run `make docker_build` from the root repo directory) or wait for 2024.4 release when the image will be published.

**Comment by tjtanaa** [comment]
> Support for `usage` has been merged to main branch. You can use it now if you build the docker image (run `make docker_build` from the root repo directory) or wait for 2024.4 release when the image will be published.

Thank you very much for the updates. I will test out the new feature within these few days. 😁
