### ISSUE TITLE
ERROR - Content error: Cannot create ShapeOf layer PriorBoxClustered_0/0_port id:519

### ISSUE THREAD

**Issue by lynx97** [openvinotoolkit/model_server#271]
I converted model from SSD object detection API (ssd_inception_v2_coco_2018_01_28). followed from `https://docs.openvinotoolkit.org/2020.3/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html`
When loading model in openvino model server. I had an error` ERROR - Content error: Cannot create ShapeOf layer PriorBoxClustered_0/0_port id:519`.
I tried some models SSD with backbones  such as mobilenetv2, resnet50 and both of them had the same error.
With model face_detection in examples, it 's ok.

**Comment by lynx97** [comment]
I had tried with CRNN_tensorflow model, it works fine. Any help?

**Comment by mzegla** [comment]
Hi @lynx97, 
I have a few questions regarding your issue:
1. Can you do inference directly with OV? Does this problem occur only with model server or also with bare OpenVINO? 
2. How do you run OVMS? Are you using docker? If so, where do you get your image from? Do you build it or pull from Docker Hub?

**Comment by lynx97** [comment]
> Hi @lynx97,
> I have a few questions regarding your issue:
> 
> 1. Can you do inference directly with OV? Does this problem occur only with model server or also with bare OpenVINO?
> 2. How do you run OVMS? Are you using docker? If so, where do you get your image from? Do you build it or pull from Docker Hub?

Thanks for your reply. I can do inference directly. This issue happens only with OVMS. 
With OVMS, I use Docker, from tutorial `docker pull openvino/ubuntu18_model_server:latest`

**Comment by mzegla** [comment]
Could you post a command you use to run OVMS? 
Also is there a way you could share your model (IR files) so I could try to reproduce this issue on my end?

**Comment by lynx97** [comment]
I convert IR model with command: 
First, I built Docker from Dockerfile followed by: [tutorial](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_docker_linux.html)
Note that I build docker for CPU. 
Then, in docker I converted with command.
`cd /opt/intel/openvino/deployment_tools/model_optimizer`
`python3 mo_tf.py --input_model /home/pre_trained_models/ssd_inception_v2_coco_2018_01_28/frozen_inference_graph.pb --data_type FP32 --output_dir /home/pre_trained_models/inception_v2/ --tensorflow_object_detection_api_pipeline_config /home/pre_trained_models/ssd_inception_v2_coco_2018_01_28/pipeline.config --log_level DEBUG --transformations_config /opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/ssd_v2_support.json --batch 1`
This is link for IR folder [IR_inceptionv2](https://drive.google.com/drive/folders/1RCOCfaO7N8vGu1QTqbt-Xc5C3dKE0G7y?usp=sharing)
I start OVMS with command: 
In Docker OVMS, from `/ie-serving-py`
`./start_server.sh ie_serving config --config_path serving_config.json --port 7001`

This is the content of `serving_config.json` file:
```
{
    "model_config_list":[
       {
          "config":{
             "name":"detection",
             "base_path":"path/to/open_vino_inceptionv2",
             "Shape": "auto",
             "batch_size": "1"
          }
       }
    ]
 }
```
I tried some variable with key Shape, batch_size but it does not work .

**Comment by mzegla** [comment]
I tried to load your model in OVMS and got the same error. 
I also tried to use it with object detection sample app from OpenVINO toolkit 
(within https://hub.docker.com/r/openvino/ubuntu18_dev container) and got the same error as in OVMS. 
I would  blame model conversion, but you said you can do inference on OV directly using those IR files. 
How did you manage to perform inference on that model? Also in docker container? Using OV samples or your own code?

**Comment by lynx97** [comment]
I tested model with sample app script provided OV samples. Have you tried to convert SSD models and loaded successfully in OVMS? If yes, Could you upload model in somewhere for me to test?
Thanks

**Comment by rasapala** [comment]
Hi @lynx97  sorry for late response. Do you need further assistance with the SSD model or have you found a working model ?
