### ISSUE TITLE
error found in home page demo TypeError: Expected Ptr<cv::UMat> for argument 'img'

### ISSUE THREAD

**Issue by zhangguobin** [openvinotoolkit/model_server#272]
OS: Ubuntu 16.04
Failed to run the last step in https://github.com/openvinotoolkit/model_server#running-the-server
Below change is needed to fix it
-img_out = cv2.rectangle(img_out,(x_min,y_min),(x_max,y_max),(0,0,255),1)
+img_out = cv2.rectangle(cv2.UMat(img_out),(x_min,y_min),(x_max,y_max),(0,0,255),1)

python face_detection.py --batch_size 1 --width 600 --height 400 --input_images_dir images --output_dir results
['people1.jpeg']
Start processing 1 iterations with batch size 1

Request shape (1, 3, 400, 600)
Response shape (1, 1, 200, 7)
image in batch item 0 , output shape (3, 400, 600)
detection 0 [[[0.         1.         1.         0.55241716 0.3024692  0.59122956
   0.39170963]]]
x_min 331
y_min 120
x_max 354
y_max 156
Traceback (most recent call last):
  File "face_detection.py", line 110, in <module>
    img_out = cv2.rectangle(img_out,(x_min,y_min),(x_max,y_max),(0,0,255),1)
TypeError: Expected Ptr<cv::UMat> for argument 'img'

**Comment by mzegla** [comment]
Done in https://github.com/openvinotoolkit/model_server/pull/273
