### ISSUE TITLE
Suggest improve document to get them consistent to help  ease the run of example_client scripts

### ISSUE THREAD

**Issue by zhangguobin** [openvinotoolkit/model_server#279]
According to the [home page](https://github.com/openvinotoolkit/model_server#running-the-server), I can successfully run model server and play the face_detection.py script.

But when I try to run other examples scripts under example_client, it does not work.
I think this is because they require different configurations when launching server
1.  model path should follow the requirements of TensorFlow Serving REST API? --model_path /v1/models/face-detection
2.  document should highlight the method to enable REST API, --rest_port, I think this will help save newbies a lot of time.
3. It would be better if have some introductions on the meaning of each docker command parameters.

**Comment by mzegla** [comment]
Thank you. We will consider including your suggestions in future release.

**Comment by dtrawins** [comment]
Documentation has been updated including examples and a quick start guide.
