### ISSUE TITLE
Is the openvino model server docker image compatible with a Raspberry Pi 4?

### ISSUE THREAD

**Issue by Steedance** [openvinotoolkit/model_server#282]
I'm trying to run the openvino model server on a Raspberry Pi 4 and after trying to run the docker image I ran into this error:

```exec user process caused "exec format error"```

Is it possible to run openvino model server on a raspberry pi? What steps would I need to take to make it work?

Thanks in advance for any help.

**Comment by mzegla** [comment]
Hi,

Sorry for late response. It should be possible to run model server on everything supported by OpenVINO. 
It sometimes requires some adjustments though. Our docker images do not include support for Raspberry Pi.
I'd assume that to make it work with Raspberry Pi, you'd need to install OpenVINO specifically for Raspberry Pi:
https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html

Unfortunately, we didn't look into requirements and dependencies required to enable OVMS on Raspberry Pi.
It's something we might look into in the future, but for now that's all I know.

**Comment by Steedance** [comment]
Hi @mzegla,

Thanks for the response. I managed to get the model server working on the Raspberry Pi by following the instructions for a bare metal installation.

We've had to include support for both bare metal and docker in our program but that's not too much of an issue. It would be cool to have a docker image that's compatible with a Raspberry Pi at some point.
