### ISSUE TITLE
Deploying YOLO models

### ISSUE THREAD

**Issue by chunzhe-intel** [openvinotoolkit/model_server#2832]
**Describe the bug**
I've encountered an issue deploying Yolov8 and Yolov11 models, where its complaining about "Error during layout configuration"

**To Reproduce**
1. Prepare the IR-formatted YOLOv8 and YOLOv11 models by following the guide in https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/yolov8-optimization and https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/yolov11-optimization, respectively.
2. Launch OVMS with the command (docker method)
```
docker run --rm -d -v $(pwd)/models:/models -p 9000:9000 -p 8000:8000 openvino/model_server:latest \
--model_name yolov8n --model_path /models/yolov8n --port 9000 --rest_port 8000 --layout NHWC:NCHW 
```
The container would crash immediately. Also tried with using a OVMS bin.
3. Error message from the OVMS bin approach
![image](https://github.com/user-attachments/assets/fda2aef2-3278-42f4-acb9-5c052f184de7)

**Expected behavior**
A fully running OVMS with Yolo models

Any help will be amazing. Thanks

**Comment by dtrawins** [comment]
@chunzhe-intel OVMS requires all the inputs and outputs to be named. Some torch models don't include the names.
The solution is to add the names to the IR model before deployment.
It can be done with the following python commands:
```
from PIL import Image
from ultralytics import YOLO
import openvino as ov
from pathlib import Path

det_model = YOLO(f"yolo11n.pt")

ir_model_dir = det_model.export(format="openvino", dynamic=True, half=True)  # it saves model without names
ov_model = ov.Core().read_model(Path(ir_model_dir + "/yolo11n.xml"))
for idx, out in enumerate(ov_model.outputs):  
   out.get_tensor().set_names({f"out_{idx}"})
ov.save_model(ov_model, "yolo11_model_with_names.xml")  # it saves model with names
```

**Comment by dtrawins** [comment]
@chunzhe-intel one more comment, you would need to use ovms 2024.5. You can build it from source now or wait till next week for the public image release.

**Comment by chunzhe-intel** [comment]
Thanks @dtrawins! It worked. I'll close this issue
