### ISSUE TITLE
Unable to load person detection model with config.json

### ISSUE THREAD

**Issue by mihir135** [openvinotoolkit/model_server#300]
My config.json,
{
   "model_config_list":[
      {
         "config":{
            "name":"face_detection",
            "base_path":"s3://bucket/2020/4/face_detection",
            "batch_size": "auto",
            "model_version_policy": {"specific": { "versions":[3] }},
			"shape": "auto"
         }
      },
      {
         "config":{
            "name":"person_detection",
            "base_path":"s3://buckets/2020/4/person_detection",
            "batch_size": "auto",
            "model_version_policy": {"specific": { "versions":[1] }},
			"shape": "auto"
         }
      }
   ]
}

The problem is the face detection model load and infers without error. But the person detection model is causing the following error.

ie_serving.models.model - ERROR - Error occurred while loading model version: {'xml_file': '/tmp/person-detection-0106.xml', 'bin_file': '/tmp/person-detection-0106.bin', 'mapping_config': None, 'version_number': 3, 'batch_size_param': None, 'shape_param': '(1,3,800,1344)', 'num_ireq': 1, 'target_device': 'CPU', 'plugin_config': None}

ie_serving.models.model - ERROR - Content error: IShapeInferExtension wasn't registered for node 668 with type ExperimentalDetectronPriorGridGenerator

**Comment by mzegla** [comment]
Hi, could you try not using **"auto"** shape in this model? It seems that dynamic reshape is not available for that model.

**Comment by mihir135** [comment]
Tried that already, as per the given documentation on the official model page. I tried to pass custom shape value as well. It still throws the same error. I am getting this error in person-detection-0106. However, person-detection-0102 works perfectly.

**Comment by mzegla** [comment]
Did you try not providing shape parameter at all? Providing custom value in shape parameter will also trigger reshape to adjust network at the model server start-up. Could you check if removing shape and batch size parameters from you configuration helps in this case? Model shall load with default configuration.

**Comment by mihir135** [comment]
No not without shape parameter, below is an example.

{
         "config":{
            "name":"person-detection-0102",
            "base_path":"s3://bucket/2020/4/person-detection-0106",
            "batch_size": "auto",
            "model_version_policy": {"specific": { "versions":[3] }},
	    "shape": "1,3,800,1344"
         }
      }

I will try as you suggested and revert back.

**Comment by mzegla** [comment]
How about:
```
{
    "config":{
        "name":"person-detection-0106",
        "base_path":"s3://bucket/2020/4/person-detection-0106",
        "model_version_policy": {"specific": { "versions":[3] }},
    }
}
```
?

I tried loading that model with just name and path parameters and it worked for me.

**Comment by mihir135** [comment]
Thanks, man!
my config,

{
   "model_config_list":[
      {
         "config":{
            "name":"person_detection",
            "base_path":"s3://bucket/2020/4/person_detection",
            "model_version_policy": {"specific": { "versions":[1] }}
         }
      }
   ]
}
This worked. But I think now I am getting an error in the detection client script.

I am using [this](https://github.com/openvinotoolkit/model_server/blob/master/example_client/face_detection.py) file.

It throws the following error. And the same error occurs with the vehicle_numberplate detection model.

Traceback (most recent call last):
  File "face_detection.py", line 85, in <module>
    output = make_ndarray(result.outputs["detection_out"])
  File "/media/test/Data/anaconda3/envs/autoserving/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py", line 593, in MakeNdarray
    tensor_dtype = dtypes.as_dtype(tensor.dtype)
  File "/media/test/Data/anaconda3/envs/autoserving/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 642, in as_dtype
    raise TypeError("Cannot convert value %r to a TensorFlow DType." %
TypeError: Cannot convert value 0 to a TensorFlow DType.

**Comment by mzegla** [comment]
Note that the script you use is just an example. 
There are lines like:

```
request.inputs["data"]
...
result.outputs["detection_out"]
...
x_min = int(detection[0,0,3] * args['width'])
y_min = int(detection[0,0,4] * args['height'])
x_max = int(detection[0,0,5] * args['width'])
y_max = int(detection[0,0,6] * args['height'])
...
```

Which contain hard-coded values and are very specific, just for that particular face-detection model we made it for.
Let me give you a few lines that you could adapt to your configuration and use to make simple request:

```
    request = predict_pb2.PredictRequest()  
    request.model_spec.name = <model_name>
    img = <your image as numpy array>
    request.inputs[<input_name_of_your_model>].CopyFrom(make_tensor_proto(img, shape=(img.shape)))
    result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs
    output = make_ndarray(result.outputs[<output_name_of_your_model>])
```

This code assumes your model has one input and one output. If your model has more inputs you can just add another
`request.inputs[<input_name_of_your_model>].CopyFrom(make_tensor_proto(img, shape=(img.shape)))`
lines with proper names and content. 
To read multiple outputs you can also add lines similar to :
`output = make_ndarray(result.outputs[<output_name_of_your_model>])`
with proper names.

https://docs.openvinotoolkit.org/latest/omz_models_intel_person_detection_0106_description_person_detection_0106.html
Here you can see that this model has one input with name "input" and two outputs with names "boxes" and "labels" (check the link for details). So in this case you have something like:

```
request.inputs["input"].CopyFrom(make_tensor_proto(img, shape=(img.shape)))
result = stub.Predict(request, 10.0) 
boxes= make_ndarray(result.outputs["boxes"])
labels= make_ndarray(result.outputs["labels"])
```

**Comment by mihir135** [comment]
Okay, thanks for the clarification. This works like charm!

I read that the mapping.json could be helpful to manage input and output names. Can you give me some examples of it?

Can I run a common script for all the models with different input and output names?

**Comment by mzegla** [comment]
About mapping config. Imagine you have a model with really weird inputs or outputs names (or both) for example:
inputs: **1039_g4d** 
outputs: **vk19313_iljk** and **999_0_123k**
(I just put some random strings here, not a real model names 😄 )
You can use mapping config to make it more human readable, by putting mapping_config.json alongside with model _xml_ and _bin_ files with following content in it:

```
{
       "inputs":  { 
            "1039_g4d":"input"
       },
       "outputs":{
            "vk19313_iljk":"output1",
            "999_0_123k":"output2"
       }
}
```

OVMS will map your custom inputs and outputs names to the real model inputs and outputs, so in you client script you could use **input**, **output1**, **output2** instead of **1039_g4d**, **vk19313_iljk** and **999_0_123k**


>>_"Can I run a common script for all the models with different input and output names?"_

Well, you can for sure parameterize  your script to take input and outputs names from command line or a file for example, but you will also need to fill the inputs with something. You also need to interpret the results that can mean something totally different depending on the model you use. So at some point you will probably want to have different logic for different models. But if you have a specific use case in mind and are going to use pretty similar models then you can parameterize quite a lot.

**Comment by mihir135** [comment]
_Sure, Thanks for the advice and help._😄
