### ISSUE TITLE
Converting espnet fastspeech model  onnx to openvino, Got bin file size 0 without any error 

### ISSUE THREAD

**Issue by HwangWonJun** [openvinotoolkit/model_server#302]
Hi, I trying to convert espnet fastspeech model pytorch to openvino model to check how much inference faster than pytorch.
So Using onnx converted model put in openvino tool. There is no error. just success log message. but I got a bin file size 0.
I checked model unsupported function have. It is clear.
What part can I check in my model?

Thanks.

**Comment by mzegla** [comment]
Hi, I believe your issue relates to Model Optimizer tool from OpenVINO Toolkit. 
I recommend you looking for help on OV repository (https://github.com/openvinotoolkit/openvino) in this case as model optimizer is not part of  the model server.
