### ISSUE TITLE
Grpc-java-client takes a lot of time.

### ISSUE THREAD

**Issue by liiitleboy** [openvinotoolkit/model_server#305]
openvino model_server can support tensorflow serving,but when I use grcp-java-client,it takes a lot of time.
when I use python,input deserialization need 0.8 ms.
when I use java,input deserialization need 38 ms.

**Comment by dtrawins** [comment]
@liiitleboy could you confirm if your java client sends the request with the data precision, which match the model precision.
There is likelihood that additional data conversion from the client precision to model precision increase the serialization time.
Is there a difference in the request format between java and python clients?

**Comment by dtrawins** [comment]
@liiitleboy today we released new version of OVMS 2021.1 which is written in c++. Could you test it with your clients? In case you still observe some slowness, it would be useful to see a snippet of the client code sending the request.

**Comment by liiitleboy** [comment]
> @liiitleboy could you confirm if your java client sends the request with the data precision, which match the model precision.
> There is likelihood that additional data conversion from the client precision to model precision increase the serialization time.
> Is there a difference in the request format between java and python clients?

Yes,I use the same input data.

java code:
`        ManagedChannel channel = ManagedChannelBuilder.forAddress("172.17.0.3", 9000).usePlaintext().build();
        PredictionServiceGrpc.PredictionServiceBlockingStub stub = PredictionServiceGrpc.newBlockingStub(channel);
        
        Predict.PredictRequest.Builder predictRequestBuilder = Predict.PredictRequest.newBuilder();
        Model.ModelSpec.Builder modelSpecBuilder = Model.ModelSpec.newBuilder();
        modelSpecBuilder.setName("test");
        modelSpecBuilder.setSignatureName("predict_image");
        predictRequestBuilder.setModelSpec(modelSpecBuilder);

        TensorProto.Builder tensorProtoBuilder = TensorProto.newBuilder();
        tensorProtoBuilder.setDtype(DataType.DT_FLOAT);

        tensorProtoBuilder.addAllFloatVal(valuelist);//ArrayList Float

        TensorShapeProto.Builder tensorShapeBuilder = TensorShapeProto.newBuilder();
        //nchw
        tensorShapeBuilder.addDim(TensorShapeProto.Dim.newBuilder().setSize(1));
        tensorShapeBuilder.addDim(TensorShapeProto.Dim.newBuilder().setSize(3));
        tensorShapeBuilder.addDim(TensorShapeProto.Dim.newBuilder().setSize(224));
        tensorShapeBuilder.addDim(TensorShapeProto.Dim.newBuilder().setSize(224));

        tensorProtoBuilder.setTensorShape(tensorShapeBuilder.build());`


python code : https://github.com/openvinotoolkit/model_server/blob/main/example_client/face_detection.py

**Comment by liiitleboy** [comment]
> @liiitleboy today we released new version of OVMS 2021.1 which is written in c++. Could you test it with your clients? In case you still observe some slowness, it would be useful to see a snippet of the client code sending the request.

same result

**Comment by liiitleboy** [comment]
> @liiitleboy there are two methods for passing the data in TensorProto object - via a list of [float values](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto#L50) or via [tensor_content](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto#L38) string. The second option represents the whole array in bytes format and it much more efficient in terms of deserialization and serialization. I don't have a complete working example in java but this [link](https://stackoverflow.com/questions/39443019/how-can-i-create-tensorproto-for-tensorflow-in-java) should give some hints about it. Using Tensor::AsProtoTensorContent should be much faster for you. Python [example](https://github.com/openvinotoolkit/model_server/blob/main/example_client/face_detection.py) is using tensor_content.

It worked.Thanks!
