### ISSUE TITLE
Received message larger than max ERROR

### ISSUE THREAD

**Issue by jsxyhelu** [openvinotoolkit/model_server#310]
Have set "--grpc_channel_arguments grpc.max_receive_message_length=104857600",but still report Error“ debug_error_string = "{"created":"@1602672141.715481155","description":"Received message larger than max (8388653 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":190,"grpc_status":8}"”It seems that the restriction has not been removed。

**Comment by dtrawins** [comment]
@jsxyhelu The limit on the server side is actually 1GB. Your logs indicate 4MB.
It seems to be client side restriction.
Could you try the following settings :
	options = [('grpc.max_receive_message_length', 100 * 1024 * 1024),('grpc.max_send_message_length', 100 * 1024 * 1024)]
	channel = grpc.insecure_channel(server_url, options = options)

**Comment by jsxyhelu** [comment]
thanks !it work!
