### ISSUE TITLE
Download specific OpenVINO version (2020.1.023)

### ISSUE THREAD

**Issue by edwardnguyen1705** [openvinotoolkit/model_server#322]
The `2020.1.023` version was installed in my host machine (`ubuntu 16.04`), now I want to build an `OpenVINO` docker image using the same `OpenVINO` version with `HDDL` device support,  but this link ( Intel Distribution of `OpenVINO` binary package) `https://registrationcenter-download.intel.com/akdlm/irc_nas/17062/l_openvino_toolkit_p_2021.0.023.tgz `is not accessible:
```
docker build -f Dockerfile --build-arg DLDT_PACKAGE_URL=https://registrationcenter-download.intel.com/akdlm/irc_nas/17062/l_openvino_toolkit_p_2021.0.023.tgz -t ie-serving-py:2020r1 .
```
 How and where I can download a specific`OpenVINO` version. Thanks for your time.

**Comment by brmarkus** [comment]
Where did you got the URL from? Are you logged-in into registrationcenter-download.intel.com?
Currently I see this URL for 2021.1:
`https://registrationcenter-download.intel.com/akdlm/irc_nas/17062/l_openvino_toolkit_p_2021.1.110.tgz`

**Comment by edwardnguyen1705** [comment]
Dear @brmarkus , 
Thanks for your response.
If the URL is in use, I cannot build a docker image with this [docker file](https://github.com/openvinotoolkit/model_server/blob/master/Dockerfile_binary_openvino). Here is the log:
```
2020-10-27 07:00:42 (10.2 MB/s) - 'l_openvino_toolkit_p_2021.1.110.tgz' saved [492269219/492269219]

Missing optional prerequisites
-- Signature verification
Warning: signature verification is disabled by user.
-- Unsupported OS
Detected operating system is not supported. Supported operating systems for this
release are: 
    - CentOS* 7 (Intel(R) 64);
    - Ubuntu* 18.04 (Intel(R) 64), 20.04 (Intel(R) 64);
    - Yocto  (Intel(R) 64);

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Removing intermediate container 172ecf424286
 ---> 546554b1d6ea
Step 11/19 : ENV HDDL_INSTALL_DIR="$DL_INSTALL_DIR/inference_engine/external/hddl"
 ---> Running in 28ca7568ec00
Removing intermediate container 28ca7568ec00
 ---> e4ab9083d646
Step 12/19 : ENV PYTHONPATH="$INSTALL_DIR/python/python3.5"
 ---> Running in 285ad1ecb6bd
Removing intermediate container 285ad1ecb6bd
 ---> 51e22c179d55
Step 13/19 : ENV LD_LIBRARY_PATH="$DL_INSTALL_DIR/inference_engine/external/tbb/lib:$DL_INSTALL_DIR/inference_engine/external/mkltiny_lnx/lib:$DL_INSTALL_DIR/inference_engine/external/hddl/lib:$DL_INSTALL_DIR/inference_engine/lib/intel64:$DL_INSTALL_DIR/ngraph/lib"
 ---> Running in 1933c770c146
Removing intermediate container 1933c770c146
 ---> 12b6629e271f
Step 14/19 : WORKDIR /ie-serving-py
 ---> Running in d53c501db056
Removing intermediate container d53c501db056
 ---> 986e29c08c10
Step 15/19 : COPY start_server.sh setup.py version requirements.txt /ie-serving-py/
COPY failed: stat /var/lib/docker/tmp/docker-builder268487493/start_server.sh: no such file or directory
```

I think the `2021.1.110` is not compatible with `Ubuntu 16.04` .
If I register and try to download, I also get the same as your URL. However, I would like to the URL point to the `2020.1.023` version.
Do you have any suggestion?

**Comment by dtrawins** [comment]
@edwardnguyen1705 Older release that you mentioned has URL
https://registrationcenter-download.intel.com/akdlm/irc_nas/16345/l_openvino_toolkit_p_2020.1.023_online.tgz

BTW I recommend you switching to the latest version of OVMS 2021.1. Its public dockerimage from openvino/model_server:2021.1 includes required HDDL plugin and libraries.
It wasn't tested on ubuntu16 with HDDL. Switching to ubuntu18 would be recommended as it would support the latest drivers for HDDL.

**Comment by edwardnguyen1705** [comment]
Dear @dtrawins ,

Thanks for the information. 

I just have an additional question: It would be possible to have a Ubuntu 18.04 docker container running on Ubuntu 16.04 host with HDDL support?

**Comment by dtrawins** [comment]
@edwardnguyen1705 the latest public image with OVMS we prepared is actually based on centos. You could run it on a host with ubuntu16. I'm just not sure of HDDL support in such configuration because some components like drivers and hddldaemon must be installed also on the host. We were testing it so far with the same OV version on the host and the docker container. I suggest giving it a try but the safest thing would to upgrading the host to ubuntu18 to have OS covered by the OpenVINO installation package with latest HDDL drivers.

**Comment by edwardnguyen1705** [comment]
@dtrawins Thanks for your time.
