### ISSUE TITLE
c++ client demo

### ISSUE THREAD

**Issue by GaussRieman** [openvinotoolkit/model_server#365]
Do you have a plan to replace the current python grpc demo with c++?

Or have you ever tested the performance between python and c++ grpc for model server?

Thx!

**Comment by dtrawins** [comment]
There shouldn't be any noticeable performance difference for the call latency the to gRPC endpoint. Even in python, all the compute intensive work is done by the libraries written in C++.  There might be some performance improvement for the data preprocessing on the client side in C++ but that depends on the use case.
Having said that I plan to add also C++ client to the examples. I'm not sure of the timeline now. Hopefully by the end of month.
Generally the same clients could be used for TFS and OVMS but as for now, the TensorProto object in the request should be formatted as [tensor_content](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto#L38).

**Comment by dtrawins** [comment]
@GaussRieman You can check the first version of the c++ client code on https://github.com/openvinotoolkit/model_server/pull/444

**Comment by GaussRieman** [comment]
Sorry for my late reply and thanks for the elegant demo!
