### ISSUE TITLE
If I modify the sever source code, how should i compile it ?

### ISSUE THREAD

**Issue by fujianhai** [openvinotoolkit/model_server#517]
excuse me，if  i modify the sever source code,  how should I compile it?   Can you provide some tutorials？ such as a build.sh file ?

**Comment by mzegla** [comment]
Hi, 
There are steps to compile OVMS in Docker - https://github.com/openvinotoolkit/model_server/blob/main/docs/developer_guide.md#step-1-compile-source-code

After running `make docker_build` a `openvino/model_server-build:latest` image is created. It's quite big, but contains all dependencies needed to build model server, so you can simply mount OVMS source code and run `bazel build //src:ovms` to compile.

**Comment by fujianhai** [comment]
@mzegla,  thanks,  I have another question ， when use docker pull openvino/model_server:latest , the docker just have 441M, may be have some errors?  docker run -it xxx can't be work !!!

**Comment by fujianhai** [comment]
@mzegla,  thanks,  I have another question ， when use docker pull openvino/model_server:latest , the docker just have 441M, may be have some errors?  docker run -it xxx can't be work !!!

**Comment by mzegla** [comment]
That's right. It's because the published image is meant to be as light as possible. It contains only what's necessary to run model server (so the stuff required to compile OVMS is not there). 
To have the image that you could get into and recompile sources you need to build the image yourself. 
Running `make docker_build` produces a bunch of images. One of them is `openvino/model_server-build:latest` which you can use to modify model server code and recompile it.

**Comment by fujianhai** [comment]
@mzegla,  thanks , i use "docker pull openvino/model_server-build:latest", but get "Error response from daemon pull access denied for openvino/model_server-build:latest, repository does not exist or may require 'docker login'" ???

**Comment by fujianhai** [comment]
@mzegla，thanks， “make docker_build” ，Where is this order executed? ， need to execute after entering docker?  i don't how to run this order ？

**Comment by mzegla** [comment]
You execute this command on your host machine. 

1. Clone model server repository with `git clone`
2. Get into model server root directory
3. Run `make docker_build`
4. When your images are built, run: `docker run -it -v ${PWD}:/ovms --entrypoint bash -p 9178:9178 openvino/model_server-build:latest` start container with interactive bash shell
5. Now that you're in the container, you can change source code (source code is mounted in the container so you can do that in the IDE on the host) and then from the container bash shell you can run `bazel build //src:ovms`

**Comment by fujianhai** [comment]
@mzegla ， thanks， Do you mean I should  follow the steps below??

1、docker pull openvino/model_server:latest
2、sudo docker run -it  openvino/model_server:latest
3、sudo docker attach openvino/model_server:latest
4、Clone model server repository with git clone
5、Get into model server root directory
6、Run make docker_build

**Comment by fujianhai** [comment]
@mzegla , thanks , I still have some questions. Do I follow the steps below? in host i don't have environment
1、docker pull openvino/model_server:latest
2、docker run -it openvino/model_server:latest
3、sudo docker attach openvino/model_server:latest
then follow ？
4、Clone model server repository with git clone
5、Get into model server root directory
6、Run make docker_build

**Comment by mzegla** [comment]
The pulling is not necessary. You don't need `openvino/model_server:latest`. 
You should clone repo to your machine (not into docker container) and run `make docker_build` directly on you machine.
It will build a bunch of images and when you have them (once `make docker_build` finishes successfully) you can go with `docker run` on `openvino/model_server-build:latest`

`make docker_build` does not simply compiles OVMS. It creates docker images like the one you would pull from dockerhub. 
One of these images is `openvino/model_server-build:latest` which contains dependencies and packages needed to rebuild model server. When you have that image you can mount the source code to the container and after modifications in the code, run `bazel build` like I mentioned earlier:

> 4. When your images are built, run: docker run -it -v ${PWD}:/ovms --entrypoint bash -p 9178:9178 openvino/model_server-build:latest start container with interactive bash shell
> 5. Now that you're in the container, you can change source code (source code is mounted in the container so you can do that in the IDE on the host) and then from the container bash shell you can run bazel build //src:ovms

**Comment by fujianhai** [comment]
@mzegla,  thank you very much ,  very good !

**Comment by mzegla** [comment]
You're welcome 😄
