### ISSUE TITLE
Using Myriad/NCS2 with Windows

### ISSUE THREAD

**Issue by Steedance** [openvinotoolkit/model_server#609]
Hi,

I've managed to get the docker image running on windows using the CPU with no issues, but I have had no luck using the myriad device.

After adding the property "target_device": "MYRIAD" to one of the models, I get the error: ERROR - Content error: Can not init Myriad device: NC_ERROR.

Is there any way to get the container to recognise and use the myriad device?

Any help would be appreciated.

**Comment by mzegla** [comment]
Hi, 

Is "ERROR - Content error: Can not init Myriad device: NC_ERROR" the only error message you got or did you see more detailed messages? Did you run OVMS with `--log_level DEBUG` argument?

**Comment by Steedance** [comment]
Okay, thanks for clarifying what the current version of model server supports.
