### ISSUE TITLE
Dynamically change configuration file

### ISSUE THREAD

**Issue by golisandeep3** [openvinotoolkit/model_server#61]
How can we dynamically add or delete new models without restarting the service ?

**Comment by mzegla** [comment]
Hi,

Once you start a service with desired models you won't be able to add or delete models without restarting a service. Models paths and version policies set at the beginning and cannot be changed after server starts. 

The only way to change what's served is with model versions. For example if you have a model in
`/opt/model` with version 1 i.e. (`/opt/model/1`), then you can place another model in let's say `/opt/model/2`. In this situation, depending on that model's version policy you can: 

- have both versions served - for model version policy **all**
- only version 2 - for model version policy **latest**

Server detects adding and removing versions and updates to match model version policy
For more details on model version policy check out https://github.com/IntelAI/OpenVINO-model-server/blob/master/docs/docker_container.md#model-version-policy

**Comment by golisandeep3** [comment]
Are there any plans to support this feature ?  I see that your apis are compatible with Tensorflow serving, it has this dynamic reconfiguration api.

**Comment by ryan-nervana** [comment]
Hi @golisandeep3, 

I am the product manager for OpenVINO Model Server. We have not enabled this feature yet. If you would like to discuss this more, please send me an email ryan.loney@intel.com. It is possible for us to enable, but will require time to develop and implement. I would like to understand your use case. 

Thank you, 

Ryan

**Comment by dtrawins** [comment]
@golisandeep3 The functionality for adding or removing the models is now added to new OVMS version 2021.1. With this new release you can just edit the config file. OVMS will detect the changes and apply the needed updates without restarting the service and impacting its availability.

**Comment by rasapala** [comment]
Request implemented.
