### ISSUE TITLE
Could you add an example of onnx in the help document? Thank you

### ISSUE THREAD

**Issue by liiitleboy** [openvinotoolkit/model_server#631]
Ovms supports onnx, but I didn't find an example

**Comment by dtrawins** [comment]
Example got documented on https://github.com/openvinotoolkit/model_server/blob/main/docs/ovms_onnx_example.md
@liiitleboy Could you confirm if this issue can be closed now?

**Comment by liiitleboy** [comment]
> Example got documented on https://github.com/openvinotoolkit/model_server/blob/main/docs/ovms_onnx_example.md
> @liiitleboy Could you confirm if this issue can be closed now?

thanks
