### ISSUE TITLE
Dynamic Batch Size and Shape in DAG Pipelines

### ISSUE THREAD

**Issue by Steedance** [openvinotoolkit/model_server#640]
Hi,

I have managed to implement a pipeline with a custom node that takes results from a face detection model and transforms the results into something an emotion detection model can use, which is great, I really like this feature.

My current client code uses batching to get more performance out of the model server and I am trying to replicate this inside the pipeline, with no success so far. For example, I would want to send 4 images into the pipeline, where the custom node would use the face detection results for each image to then output all of the faces detected across all of the images into the emotion detection model. I have not managed to get this working using a fixed nor dynamic batch size.

My first question is, is the above example possible?

If so, how can I adjust the batch size or shape of the face detection model if the DAG pipeline limits batch size when using demultiplexer nodes?

My current model server config, which works well with a single input image, is:

```
{
   "model_config_list":[
      {
         "config":{
            "name":"face-detection-retail-0004",
            "base_path":"/opt/test/face-detection-retail-0004"
         }
      },
      {
         "config":{
            "name":"emotions-recognition-retail-0003",
            "base_path":"/opt/test/emotions-recognition-retail-0003",
            "shape": "(1, 3, 64, 64)"
         }
      }
   ],
   "custom_node_library_config_list": [
        {
            "name": "andyTestNode",
            "base_path": "/opt/test/lib/libcustom_node_andyTest.so"
        }
    ],
   "pipeline_config_list": [
      {
        "name": "fullFace",
        "inputs": ["image", "fullSizeImage"],
        "nodes": [
            {
                "name": "faceDetection",
                "model_name": "face-detection-retail-0004",
                "version": 2,
                "type": "DL model",
                "inputs": [
                    {"data": {"node_name": "request",
                               "data_item": "image"}}
                ], 
                "outputs": [
                    {"data_item": "detection_out",
                     "alias": "faceDetections"}
                ]
            },
            {
                "name": "customNode",
                "library_name": "andyTestNode",
                "type": "custom",
                "demultiply_count": 0,
                "params": {
                    "original_image_width": "640",
                    "original_image_height": "480",
                    "target_image_width": "64",
                    "target_image_height": "64",
                    "debug": "true",
                    "imOutputDir": "/home/ovms"
                },
                "inputs": [
                    {"image": {"node_name": "request",
                               "data_item": "image"}},
                    {"faceDetections": {"node_name": "faceDetection",
                                "data_item": "faceDetections"}},
                    {"fullSizeImage": {"node_name": "request",
                                "data_item": "fullSizeImage"}}
                ],
                "outputs": [
                    {"data_item": "faceImages",
                     "alias": "faces"},
                    {"data_item": "formattedFaceDetections",
                     "alias": "faceDetections"}
                ]
            },
            {
                "name": "emotions",
                "model_name": "emotions-recognition-retail-0003",
                "type": "DL model",
                "inputs": [
                    {"data": {"node_name": "customNode",
                               "data_item": "faces"}}
                ], 
                "outputs": [
                    {"data_item": "prob_emotion",
                     "alias": "emotion"}
                ]
            }
        ],
        "outputs": [
            {"boundingBoxes": {"node_name": "customNode",
                       "data_item": "faceDetections"}},
            {"faces": {"node_name": "customNode",
                       "data_item": "faces"}},
            {"emotion": {"node_name": "emotions",
                       "data_item": "emotion"}}
        ]
      }
   ]
}

```

Trying to change the batch size or shape of the face detection model produces errors, adding "shape": "auto" gives a shape forbidden error and adding "shape": "(2, 3, 300, 300)" gives the error:
```
[modelmanager][error][pipelinedefinition.cpp:361] Pipeline: fullFace, node: faceDetection, inputName: data, inputShape: (2,3,300,300). Batch size >= 2 is not allowed for non gathering nodes
```

Any help on how to set up the model server config would be appreciated.

Andy

**Comment by atobiszei** [comment]
Hi,

We are happy with your positive feedback :).

> I would want to send 4 images into the pipeline, where the custom node would use the face detection results for each image to then output all of the faces detected across all of the images into the emotion detection model. I have not managed to get this working using a fixed nor dynamic batch size.
> 
> My first question is, is the above example possible?

There is no possibility to change batch size to 2 if you use demultiplexer. Sending batch size > 1 could be impractical since you could have different number of faces detected on each image. Then the DAG would have to pack those which creates ambiguity how the output shape would look like since you should still be able to know from which image your detection was.

> If so, how can I adjust the batch size or shape of the face detection model if the DAG pipeline limits batch size when using demultiplexer nodes?
You can edit the shape (just keep batch size equal 1).
`"shape": "(1, 3, 300, 300)"`

If you are working on improving performance you could try:
- sending multiple requests with batch 1 simultaneously
- changing `CPU_THROUGHPUT_STREAMS` or/and `nireq` configuration per model (it may be called DEVICE_TYPE_THROUGHPUT_STREAMS - depends on hardware on which you run inference).

So for example for face-detection model you would change config to something like this:
```
         "config":{
            "name":"face-detection-retail-0004",
            "base_path":"/opt/test/face-detection-retail-0004"
            "plugin_config": {
                  "CPU_THROUGHPUT_STREAMS":  "4"
             }
            "nireq": 16
         }
```
What the values should be is dependent on hardware used. I gave 4/16 as an example here.

If we would have more details about the use case then we could advise more. With current information we think that sending multiple requests simultaneously is the best path here.

Adrian

**Comment by Steedance** [comment]
Hi,

Thanks for the response.

I have a couple of questions regarding using asynchronous call with the model server. I have used the "CPU_THROUGHPUT_STREAMS" and "nireq" properties before so I recognise the example config you posted. Does this mean that setting the model to handle async requests will allow the pipeline to handle async requests? Meaning I don't need to add anything to the "pipeline_config_list" property? Also would I need to set these two properties for each model in the pipeline or just the entry node for the pipeline?

Andy

**Comment by atobiszei** [comment]
> Does this mean that setting the model to handle async requests will allow the pipeline to handle async requests?

All predict requests calls to OVMS are blocking (client need to wait for response), but the predictions themselves are running in parallel. `CPU_THROUGHPUT_STREAMS` is defining how many parallel inferences is happening, `nireq` is defining how many parallel predictions can be "prepared" for execution.

Pipelines use the same `CPU_THROUGHPUT_STREAMS`/`nireq` pool to execute inferences, but each inference in pipeline can occur simultaneously if it has required inputs ready.

> Meaning I don't need to add anything to the "pipeline_config_list" property

You don't have to add anything to pipeline_config_list. Both parameters are for model configuration.

> Also would I need to set these two properties for each model in the pipeline or just the entry node for the pipeline?

You need to define those parameters for all models used in pipeline.

Up to some point higher throughput streams means that you can process more inferences at a time so it increases throughput at the cost of latency. Default values for those parameters are compromise, but you can optimize towards one or the other.

**Comment by Steedance** [comment]
Hi,

Thanks for clarifying that, it was very helpful.

Andy

**Comment by rasapala** [comment]
@Steedance Let us know if you need more information or we can close this issue.
