### ISSUE TITLE
Missing Dockerfile for building model server on top of ubuntu 18.04/20.04

### ISSUE THREAD

**Issue by pctseng7** [openvinotoolkit/model_server#650]
By following the instruction, I tried to use "make docker_build" on my ubuntu machine to build openvino model server. However, only centos and redhat dockerfile are shown in the repo. Please kindly add dockerfile for ubuntu, thanks! 

If there is plan to support ubuntu based docker image on docker hub registry, that will be great also, thanks.

**Comment by pedromoraesh** [comment]
Any updates for the docker image on the docker hub?

**Comment by dtrawins** [comment]
We are planning to switch dockerhub docker image to be ubuntu 20.04 based instead of centos starting from release 2022.1 planned for September 2021.
Dockerfile with ubuntu base image will be most likely published much earlier.
