### ISSUE TITLE
Feature Request: Hardware Usage Information.

### ISSUE THREAD

**Issue by Steedance** [openvinotoolkit/model_server#695]
Hi,

I think it would be useful to be able to query the model server to get hardware information and usage. For example in Openvino runtime it is possible to get the temperature of a Myriad device, it would be useful if this information was available through the model server (when a myriad device is used). 

Also being able to get general usage stats could be useful, things like amount of inferences completed, average inference time. This could be split by hardware.

Would it be possible to add this functionality?

Andy

**Comment by mzegla** [comment]
Hi Andy,

We can see the value in adding such feature and we would like to implement it at some point in the future, but I cannot give you any timeframe when we could possibly deliver. Not in the nearest future for sure.
