### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by jhagege** [openvinotoolkit/model_server#724]
Hi,
Is there a recommended way to healthcheck the openvino model server ? 
We are trying to implement monitoring to make sure our service is reliable.
Thanks for any insights.

**Comment by dtrawins** [comment]
@jhagege one option is to follow the method in kubernetes readiness test https://github.com/openvinotoolkit/model_server/blob/main/deploy/ovms/templates/deployment.yaml#L51 
It checks if the gRPC port is responding. It is a sign that the configuration and initial models are loaded and ready for serving.

Another option could be with using REST API calls testing the status of individual models. https://github.com/openvinotoolkit/model_server/blob/main/docs/model_server_rest_api.md#model-status 
You could also use the response from config status to report all models at once https://github.com/openvinotoolkit/model_server/blob/main/docs/model_server_rest_api.md#config-status
