### ISSUE TITLE
Custom pipeline broken when batch size greater than 1

### ISSUE THREAD

**Issue by carlosmonteirobefore** [openvinotoolkit/model_server#737]
Hi,
I have a custom pipeline break when model_zoo_intel_object_detection crop two or more images to landmarks_regression_retail_0009, does anyone have ideas to solve this problem? I
 tried modify batch_size in model config but haven't get anywhere. 
this is the custom_config.json

<details><summary>My Custom JSON</summary>

```JSON
{
    "model_config_list": [
        {
            "config": {
                "name": "face_detection_model",
                "base_path": "/models/face-detection"
            }
        },
        {
            "config": {
                "name": "face_recognition_model",
                "base_path": "/models/face-reidentification"
            }
        },
        {
            "config": {
                "name": "face_landmarks_model",
                "base_path": "/models/landmarks"
            }
        },
        {
            "config": {
                "name": "person_detection_model",
                "base_path": "/models/person-detection"
            }
        },
        {
            "config": {
                "name": "emotions_recognition_model",
                "base_path": "/models/emotions"
            }
        },
        {
            "config": {
                "name": "age_gender_recognition_model",
                "base_path": "/models/age-gender",
                "shape" : "(1,3,64,64)"
            }
        }
    ],

    "custom_node_library_config_list": [
        {"name": "image_transformation_custom",
            "base_path": "/ovms/lib/libcustom_node_image_transformation.so"},
        {"name": "object_detection_image_extractor_custom",
            "base_path": "/ovms/lib/libcustom_node_model_zoo_intel_object_detection.so"}
    ],
    
    "pipeline_config_list": [
        {
            "name": "face_recognition_pipeline",
            "inputs": ["image"],
            
            "nodes":[
                {
                    "name": "face_detection_node",
                    "model_name": "face_detection_model",
                    "type": "DL model",
                    "inputs": [
                        {"image": {
                            "node_name": "request",
                            "data_item": "image"}}],
                    "outputs": [
                        {"data_item": "detection_out",
                            "alias": "face_rois_out"}]
                },
                  
                {
                    "name": "extract_node",
                    "library_name": "object_detection_image_extractor_custom",
                    "type": "custom",
                    "params": {
                        "original_image_width": "256",
                        "original_image_height": "256",
                        "target_image_width": "48",
                        "target_image_height": "48",
                        "convert_to_gray_scale": "false",
                        "max_output_batch": "1",
                        "confidence_threshold": "0.7",
                        "debug": "true"
                    },
                    "inputs": [
                        {"image": {
                                "node_name": "request",
                                "data_item": "image"}},
                        {"detection": {
                                "node_name": "face_detection_node",
                                "data_item": "face_rois_out"}}],
                    "outputs": [
                        {"data_item": "images",
                            "alias": "face_image_out"},
                        {"data_item": "coordinates",
                            "alias": "face_coordinates_out"},
                        {"data_item": "confidences",
                            "alias": "confidence_levels_out"}]
                },
                
                
                {
                    "name": "face_landmark_node",
                    "model_name": "face_landmarks_model",
                    "type": "DL model",
                    "inputs": [
                        {"0": {
                                "node_name": "extract_node",
                                "data_item": "face_image_out"}}],
                    "outputs": [
                        {"data_item": "95",
                            "alias": "face_landmarks_out"}]
                },

                {
                    "name": "image_transformation_node",
                    "library_name": "image_transformation_custom",
                    "type": "custom",
                    "params": {
                        "make_transform": "true",

                        "target_image_width": "128",
                        "target_image_height": "128",

                        "original_image_color_order": "BGR",
                        "target_image_color_order": "BGR",

                        "original_image_layout": "CHW",
                        "target_image_layout": "CHW",

                        "debug": "true"

                    },
                    "inputs": [
                        {"image": {
                                "node_name": "extract_node",
                                "data_item": "face_image_out"}},
                        {"landmarks": {
                                "node_name": "face_landmark_node",
                                "data_item": "face_landmarks_out"}}],
                    "outputs": [
                        {"data_item": "image",
                            "alias": "transformed_image_out"}]
                },
                
                
                {
                    "name": "face_embedding_node",
                    "model_name": "face_recognition_model",
                    "type": "DL model",
                    "inputs": [
                        {"0": {
                            "node_name": "image_transformation_node",
                            "data_item": "transformed_image_out"}}],
                    "outputs": [
                        {"data_item": "658/add_",
                        "alias": "embeddings_out"}]
                }
            
            
            ],
            "outputs": [
                {"embeddings": {
                        "node_name": "face_embedding_node",
                        "data_item": "embeddings_out"}},

                {"face_landmarks": {
                        "node_name": "face_landmark_node",
                        "data_item": "face_landmarks_out"}},

                {"transformed_image": {
                        "node_name": "image_transformation_node",
                        "data_item": "transformed_image_out"}},

                {"face_crop": {
                        "node_name": "face_detection_node",
                        "data_item": "face_rois_out"}},
                
                {"face_image": {
                    "node_name": "extract_node",
                    "data_item": "face_image_out"}},

                {"face_coordinates": {
                    "node_name": "extract_node",
                    "data_item": "face_coordinates_out"}},

                {"confidence_levels": {
                    "node_name": "extract_node",
                    "data_item": "confidence_levels_out"}}
            ]
        }
    ]
}
```

</details>

**Comment by pedromoraesh** [comment]
Same problem here!

I had to comment line `model_zoo_intel_object_detection.cpp` [96](https://github.com/openvinotoolkit/model_server/blob/main/src/custom_nodes/model_zoo_intel_object_detection/model_zoo_intel_object_detection.cpp#L64) and [309](https://github.com/openvinotoolkit/model_server/blob/main/src/custom_nodes/model_zoo_intel_object_detection/model_zoo_intel_object_detection.cpp#L309) because they were giving some weird errors in pipeline like: Model A has (0,1,3,256,256) shape with Model B (1,3,256,256). Even if i remove `demultiply_count`. 

In the end, the pipeline works for One Object, but if I have two or more it fails due to batch_size, with the original implementation I was no able to create the pipeline due to shape mismatch between nodes.

**Comment by atobiszei** [comment]
Hello @carlosmonteirobefore,
 
> I have a custom pipeline break when model_zoo_intel_object_detection crop two or more images to landmarks_regression_retail_0009, does anyone have ideas to solve this problem?

I assume that you will have variable number of object detected. In that case you have to use demultiplexer in order for this DAG to work. You need to add parameter to node that is extracting images `"demultiply_count": 0`.

Additionally you did set the parameter `"max_output_batch" = "1"` this have to be adjusted as well. Idea for this parameter in example custom node is to limit maximal number of detected objects. If for some reason unreasonable number of objects is detected then this will limit the impact of such cases.

> I tried modify batch_size in model config but haven't get anywhere.
> this is the custom_config.json
> 
> My Custom JSON
> ```json
> {
>     "model_config_list": [
>         {
>             "config": {
>                 "name": "face_detection_model",
>                 "base_path": "/models/face-detection"
>             }
>         },
>         {
>             "config": {
>                 "name": "face_recognition_model",
>                 "base_path": "/models/face-reidentification"
>             }
>         },
>         {
>             "config": {
>                 "name": "face_landmarks_model",
>                 "base_path": "/models/landmarks"
>             }
>         },
>         {
>             "config": {
>                 "name": "person_detection_model",
>                 "base_path": "/models/person-detection"
>             }
>         },
>         {
>             "config": {
>                 "name": "emotions_recognition_model",
>                 "base_path": "/models/emotions"
>             }
>         },
>         {
>             "config": {
>                 "name": "age_gender_recognition_model",
>                 "base_path": "/models/age-gender",
>                 "shape" : "(1,3,64,64)"
>             }
>         }
>     ],
> 
>     "custom_node_library_config_list": [
>         {"name": "image_transformation_custom",
>             "base_path": "/ovms/lib/libcustom_node_image_transformation.so"},
>         {"name": "object_detection_image_extractor_custom",
>             "base_path": "/ovms/lib/libcustom_node_model_zoo_intel_object_detection.so"}
>     ],
>     
>     "pipeline_config_list": [
>         {
>             "name": "face_recognition_pipeline",
>             "inputs": ["image"],
>             
>             "nodes":[
>                 {
>                     "name": "face_detection_node",
>                     "model_name": "face_detection_model",
>                     "type": "DL model",
>                     "inputs": [
>                         {"image": {
>                             "node_name": "request",
>                             "data_item": "image"}}],
>                     "outputs": [
>                         {"data_item": "detection_out",
>                             "alias": "face_rois_out"}]
>                 },
>                   
>                 {
>                     "name": "extract_node",
>                     "library_name": "object_detection_image_extractor_custom",
>                     "type": "custom",
>                     "demultiply_count": 0,    ##### This is required for demultiplexing
>                     "params": {
>                         "original_image_width": "256",
>                         "original_image_height": "256",
>                         "target_image_width": "48",
>                         "target_image_height": "48",
>                         "convert_to_gray_scale": "false",
>                         "max_output_batch": "1",   ##### This have to be adjusted -> this is setting limit for number of following inferences to occur
>                         "confidence_threshold": "0.7",
>                         "debug": "true"
>                     },
>                     "inputs": [
>                         {"image": {
>                                 "node_name": "request",
>                                 "data_item": "image"}},
>                         {"detection": {
>                                 "node_name": "face_detection_node",
>                                 "data_item": "face_rois_out"}}],
>                     "outputs": [
>                         {"data_item": "images",
>                             "alias": "face_image_out"},
>                         {"data_item": "coordinates",
>                             "alias": "face_coordinates_out"},
>                         {"data_item": "confidences",
>                             "alias": "confidence_levels_out"}]
>                 },
>                 
>                 
>                 {
>                     "name": "face_landmark_node",
>                     "model_name": "face_landmarks_model",
>                     "type": "DL model",
>                     "inputs": [
>                         {"0": {
>                                 "node_name": "extract_node",
>                                 "data_item": "face_image_out"}}],
>                     "outputs": [
>                         {"data_item": "95",
>                             "alias": "face_landmarks_out"}]
>                 },
> 
>                 {
>                     "name": "image_transformation_node",
>                     "library_name": "image_transformation_custom",
>                     "type": "custom",
>                     "params": {
>                         "make_transform": "true",
> 
>                         "target_image_width": "128",
>                         "target_image_height": "128",
> 
>                         "original_image_color_order": "BGR",
>                         "target_image_color_order": "BGR",
> 
>                         "original_image_layout": "CHW",
>                         "target_image_layout": "CHW",
> 
>                         "debug": "true"
> 
>                     },
>                     "inputs": [
>                         {"image": {
>                                 "node_name": "extract_node",
>                                 "data_item": "face_image_out"}},
>                         {"landmarks": {
>                                 "node_name": "face_landmark_node",
>                                 "data_item": "face_landmarks_out"}}],
>                     "outputs": [
>                         {"data_item": "image",
>                             "alias": "transformed_image_out"}]
>                 },
>                 
>                 
>                 {
>                     "name": "face_embedding_node",
>                     "model_name": "face_recognition_model",
>                     "type": "DL model",
>                     "inputs": [
>                         {"0": {
>                             "node_name": "image_transformation_node",
>                             "data_item": "transformed_image_out"}}],
>                     "outputs": [
>                         {"data_item": "658/add_",
>                         "alias": "embeddings_out"}]
>                 }
>             
>             
>             ],
>             "outputs": [
>                 {"embeddings": {
>                         "node_name": "face_embedding_node",
>                         "data_item": "embeddings_out"}},
> 
>                 {"face_landmarks": {
>                         "node_name": "face_landmark_node",
>                         "data_item": "face_landmarks_out"}},
> 
>                 {"transformed_image": {
>                         "node_name": "image_transformation_node",
>                         "data_item": "transformed_image_out"}},
> 
>                 {"face_crop": {
>                         "node_name": "face_detection_node",
>                         "data_item": "face_rois_out"}},
>                 
>                 {"face_image": {
>                     "node_name": "extract_node",
>                     "data_item": "face_image_out"}},
> 
>                 {"face_coordinates": {
>                     "node_name": "extract_node",
>                     "data_item": "face_coordinates_out"}},
> 
>                 {"confidence_levels": {
>                     "node_name": "extract_node",
>                     "data_item": "confidence_levels_out"}}
>             ]
>         }
>     ]
> }
> ```

**Comment by atobiszei** [comment]
Hello @pedromoraesh

Custom nodes that are extracting images are to be used with demultiplexer. They intentionally produce outputs with additional dimension that is later on stripped by demultiplexing.

> Model A has (0,1,3,256,256) shape with Model B (1,3,256,256)

If you are not using the demultiplexer then the first dimension will not be stripped. In cases when you always have the same number of objects detected you could rewrite the custom node to omit adding this additional dimension and then follow this up with model that is handling just that one batch size on input. However then you loose flexibility.

**Comment by pedromoraesh** [comment]
Hello @atobiszei 

Using the @carlosmonteirobefore pipeline as an example, I should put `demultiply_count` into Model_zoo_object_detection, face_landmark_model, and image_transformation_node, once all they will output dynamically according to face_detection_model? Then all the outputs are going to be with 5 dimensions.

In the end, I need to use `gathering`  to put all the results into the output

**Comment by atobiszei** [comment]
Hello @pedromoraesh

I think that in this case the problem is feeding pipeline output by the output of FaceDetection node.
![Screen Shot 2021-07-01 at 15 30 46](https://user-images.githubusercontent.com/36039266/124133522-341f4400-da82-11eb-8426-c2c4bf86f9e6.png)

The issue here is that the output of Face Detection node is not demutiplied but is then gathered by DAG in the exit node which is not supported.

So you have to remove `face_crop` pipeline output and then check again if there will be additional error logged. As per error you got I admit it could be more self-explanatory.

I marked in config lines to remove

```
{
            "name":"face_recognition_pipeline",
            "inputs":[
                "image"
            ],
            "nodes":[
                {
                    "name":"face_detection_node",
                    "model_name":"face_detection_model",
                    "type":"DL model",
                    "inputs":[
                        {
                            "image":{
                                "node_name":"request",
                                "data_item":"image"
                            }
                        }
                    ],
                    "outputs":[
                        {
                            "data_item":"detection_out",
                            "alias":"face_rois_out"
                        }
                    ]
                },
                {
                    "name":"extract_node",
                    "library_name":"object_detection_image_extractor_custom",
                    "type":"custom",
                    "demultiply_count": 0, // Added this one
                    "params":{
                        "original_image_width":"256",
                        "original_image_height":"256",
                        "target_image_width":"48",
                        "target_image_height":"48",
                        "convert_to_gray_scale":"false",
                        "max_output_batch":"100", // Added this one
                        "confidence_threshold":"0.7",
                        "debug":"true"
                    },
                    "inputs":[
                        {
                            "image":{
                                "node_name":"request",
                                "data_item":"image"
                            }
                        },
                        {
                            "detection":{
                                "node_name":"face_detection_node",
                                "data_item":"face_rois_out"
                            }
                        }
                    ],
                    "outputs":[
                        {
                            "data_item":"images",
                            "alias":"face_image_out"
                        },
                        {
                            "data_item":"coordinates",
                            "alias":"face_coordinates_out"
                        },
                        {
                            "data_item":"confidences",
                            "alias":"confidence_levels_out"
                        }
                    ]
                },
                {
                    "name":"face_landmark_node",
                    "model_name":"face_landmarks_model",
                    "type":"DL model",
                    "inputs":[
                        {
                            "0":{
                                "node_name":"extract_node",
                                "data_item":"face_image_out"
                            }
                        }
                    ],
                    "outputs":[
                        {
                            "data_item":"95",
                            "alias":"face_landmarks_out"
                        }
                    ]
                },
                {
                    "name":"image_transformation_node",
                    "library_name":"image_transformation_custom",
                    "type":"custom",
                    "params":{
                        "make_transform":"true",
                        "target_image_width":"128",
                        "target_image_height":"128",
                        "original_image_color_order":"BGR",
                        "target_image_color_order":"BGR",
                        "original_image_layout":"CHW",
                        "target_image_layout":"CHW",
                        "debug":"true"
                    },
                    "inputs":[
                        {
                            "image":{
                                "node_name":"extract_node",
                                "data_item":"face_image_out"
                            }
                        },
                        {
                            "landmarks":{
                                "node_name":"face_landmark_node",
                                "data_item":"face_landmarks_out"
                            }
                        }
                    ],
                    "outputs":[
                        {
                            "data_item":"image",
                            "alias":"transformed_image_out"
                        }
                    ]
                },
                {
                    "name":"face_embedding_node",
                    "model_name":"face_recognition_model",
                    "type":"DL model",
                    "inputs":[
                        {
                            "0":{
                                "node_name":"image_transformation_node",
                                "data_item":"transformed_image_out"
                            }
                        }
                    ],
                    "outputs":[
                        {
                            "data_item":"658/add_",
                            "alias":"embeddings_out"
                        }
                    ]
                }
            ],
            "outputs":[
                {
                    "embeddings":{
                        "node_name":"face_embedding_node",
                        "data_item":"embeddings_out"
                    }
                },
                {
                    "face_landmarks":{
                        "node_name":"face_landmark_node",
                        "data_item":"face_landmarks_out"
                    }
                },
                {
                    "transformed_image":{
                        "node_name":"image_transformation_node",
                        "data_item":"transformed_image_out"
                    }
                },
                {  ### To remove      
                    "face_crop":{  ### To remove      
                        "node_name":"face_detection_node",  ### To remove      
                        "data_item":"face_rois_out"  ### To remove      
                    } ### To remove      
                },   ### To remove      
                {
                    "face_image":{
                        "node_name":"extract_node",
                        "data_item":"face_image_out"
                    }
                },
                {
                    "face_coordinates":{
                        "node_name":"extract_node",
                        "data_item":"face_coordinates_out"
                    }
                }
            ]
        },
```

**Comment by pedromoraesh** [comment]
@atobiszei Well Done Sir, the pipeline is AVAILABLE now and it works. :rocket: 

I had to either remove `transformed_image` from **output** due to shards problems:
``` JSON

{
    "transformed_image":{
        "node_name":"image_transformation_node",
        "data_item":"transformed_image_out"
     }
}

```


`image_transformation.cpp` was reporting problems with shards that don't have the same description because the layout of the current shard is ANY and the first shard CHW, it's weird because in this node we do transform (in the case we maintain) the layout to CHW based on parameters and with only one object it works... I found the Layout == ANY in [tensorinfo.cpp](https://github.com/openvinotoolkit/model_server/blob/main/src/tensorinfo.cpp#L34)

I did take a look into the [gathernodeinputhandler.cpp](https://github.com/openvinotoolkit/model_server/blob/main/src/gathernodeinputhandler.cpp#L52) and saw that there is a comparison between two Tensordescriptions that came from and IE Module.

This is the error. I tried reverse engineering but when I need to go into IE Module it will take too much time.
![image](https://user-images.githubusercontent.com/16081608/124152190-4fc62280-da61-11eb-907f-d41cee99d2da.png)

If you can give me some explanation about those shards, just to understand better the error I would be appreciated.



In the end, I would like to thank you in my name and from @carlosmonteirobefore  for all the support you did to our problem. It's not common in git to see that attention coming from big companies like INTEL. :metal:

**Comment by atobiszei** [comment]
> If you can give me some explanation about those shards, just to understand better the error I would be appreciated.

This time the issue seems to be on our side. I have idea how the fix should look like. It seems that we do the validation of shards too soon before gathering (we do it when we setInput for the gathering node, while we should delay that check just before shards merging). This will occur if you have pipeline that:

NodeA(demultiplexer) -> demultiplexerOutput
-> demultiplexerOutput -> customNode
-> demultiplexerOutput -> modelNode

Good that you were able to workaround this issue on your own.

> @atobiszei Well Done Sir, the pipeline is AVAILABLE now and it works. 🚀

> In the end, I would like to thank you in my name and from @carlosmonteirobefore for all the support you did to our problem. It's not common in git to see that attention coming from big companies like INTEL. 🤘

Good to hear that. Thanks! :)

**Comment by carlosmonteirobefore** [comment]
Another time me and @pedromoraesh would like to say thanks for the help you gave us.
I'm really impressed in how fast and dedicated to help in the best way as possible.
