### ISSUE TITLE
GRPC Issue, unable to inference using GRPC through IPv4 address

### ISSUE THREAD

**Issue by ParthM-GitHub** [openvinotoolkit/model_server#753]
I have set up OVMS with nginx security. I am unable to perform inferencing using GRPC.

When using localhost and port 9000, it works. But if I use IPv4 or even 127.0.0.1 instead of localhost

Generating the certificate with public IPv4, running the container with IPv4 as well. Using the following command is not working.
```sh
python3 ~/grpc_client.py --grpc_port <grpc_port> --batch_size 1 --model_name vehicle-detection --width 600 --height 400 --input_images_dir ~/vehicle-detection/input/ --grpc_address <public IPv4> --input_name data --tls --server_cert server.pem --client_cert client.pem --client_key client.key 
```

But when I generate certificates with localhost and run container with localhost GRPC is working fine and also use localhost argument as --grpc_address parameter.

Below is the command I am using to start the container.

```sh

sudo docker run --rm -it -u $(id -u):$(id -g) \
        --name ec2-user \
        -v ~/vehicle-detection/models/model/vehicle-detection/:/models/vehicle-detection/ \
        -v ~/model_server-main/extras/nginx-mtls-auth/server.pem:/certs/server.pem:ro \
        -v ~/model_server-main/extras/nginx-mtls-auth/server.key:/certs/server.key:ro \
        -v ~/model_server-main/extras/nginx-mtls-auth/client_cert_ca.pem:/certs/client_cert_ca.pem:ro \
        -v ~/model_server-main/extras/nginx-mtls-auth/dhparam.pem:/certs/dhparam.pem:ro \
        -v ~/model_server-main/extras/nginx-mtls-auth/client_cert_ca.crl:/certs/client_cert_ca.crl:ro \
        -p <grpc_port>:<grpc_port> \
        -p <rest port>:<rest port> \
        openvino/model_server:nginx-mtls \
        --model_path /models/vehicle-detection --model_name vehicle-detection --grpc_bind_address <public IPv4> --port <grpc_port> --rest_bind_address <public IPv4> --rest_port <rest port> --log_level DEBUG --shape auto

```
Getting the following error.

```sh
Start processing 1 iterations with batch size 1

Request shape (1, 3, 400, 600)
Traceback (most recent call last):
  File "/home/ec2-user/grpc_client.py", line 164, in <module>
    result = stub.Predict(request, 1) # result includes a dictionary with all model outputs
  File "/home/ec2-user/.local/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1625478075.702790601","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1625478075.702785258","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
```

Details of the machine are as below:
```
   Static hostname: ************
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ************
           Boot ID: ************
    Virtualization: xen
  Operating System: Amazon Linux 2
       CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2
            Kernel: Linux 4.14.232-177.418.amzn2.x86_64
      Architecture: x86-64
```

**Comment by mzegla** [comment]
Does model server start correctly? Do you experience such behavior when you run the same setup but without nginx (with regular model server image and no TLS in the client)?

**Comment by ParthM-GitHub** [comment]
Yes, with or witout nginx I can't use grpc. Only way it is working is with localhost as mentioned in the issue, not even 127.0.0.1 is working.

**Comment by ParthM-GitHub** [comment]
Hey @rasapala @mzegla 

any updates on the issue?

**Comment by dtrawins** [comment]
@ParthM-GitHub The root cause of the connectivity errors most likely is in the server certificate common name. When you generate the certificate with the CN=localhost in https://github.com/openvinotoolkit/model_server/blob/main/extras/nginx-mtls-auth/generate_certs.sh#L26 , the client will be able to connect using that grpc_address name.
While you need to connect remotely to the https endpoint, you need to generate the server certificate common name which matches the DNS name of the host with OVMS service. On the client side, use the grpc_address with the same name.
GRPC client is not establishing the connection when the certificate is not matched for security reasons.

**Comment by ParthM-GitHub** [comment]
Hey @dtrawins 
I am replacing localhost with public IPv4 at https://github.com/openvinotoolkit/model_server/blob/main/extras/nginx-mtls-auth/generate_certs.sh#L26, https://github.com/openvinotoolkit/model_server/blob/main/extras/nginx-mtls-auth/generate_certs.sh#L32 and also at the end of openssl_ca.conf file https://github.com/openvinotoolkit/model_server/blob/main/extras/nginx-mtls-auth/openssl_ca.conf, I am appending public IPv4 with IP.1 = <ipv4>
Can you please elaborate what am I doing wrong or what more is required?

**Comment by ParthM-GitHub** [comment]
Here is the debug output that will probably help you more understand.
```json
{"created":"@1627455727.266672458","description":"Peer name <public ipv4> is not in peer certificate","file":"src/core/lib/security/security_connector/ssl/ssl_security_connector.cc","file_line":57}
I0728 07:02:07.266784538     664 subchannel.cc:1012]         Connect failed: {"created":"@1627455727.266672458","description":"Peer name <public ipv4> is not in peer certificate","file":"src/core/lib/security/security_connector/ssl/ssl_security_connector.cc","file_line":57}
```

**Comment by dtrawins** [comment]
@ParthM-GitHub using IP address in the common name will not work with those steps. You need to use a DNS name in the certificate CommonName. If you don't have the DNS name assigned in your host you could just add it in /etc/hosts.
Alternatively you could adjust the grpc client to take advantage of ssl_target_name_override grpc connection option:
```creds = grpc.ssl_channel_credentials(root_certificates=server_ca_cert,
                                         private_key=client_key, certificate_chain=client_cert)
cert_cn = "localhost"
options = (('grpc.ssl_target_name_override', cert_cn,),)
channel = grpc.secure_channel(address, creds, options)
```
That way you could keep using a certification and any CommonName and use IP address as the grpc_address value. The client will validate if the server certificate match with the ssl_target_name_override.

For production usage it is recommended to use DNS name in the certificate name.
