### ISSUE TITLE
Need of  Understanding of Demultiplexer workflow 

### ISSUE THREAD

**Issue by bhargav-sudo** [openvinotoolkit/model_server#765]
Hi,

In a project of Analysis of multiple faces in single image frame request. I want to understand the workflow of demultiplexer. It looks a little bit confusing. Because I am learning.

After detecting the face images in this below input. There are total 10 face images in the below input. so , demultiplexer creates a total of 10 requests with the shape.
Note : I had changed **demultiply_count from 0 to 10** in **config.JSON** file for better understanding of shapes of input and output of a node. It does works after change to 10.

My question is : 

After completion of face_detection node and the custom node we are resizing the face_Image to the shape of   **[10 , 1 , 64 , 64 , 3]**  and this shape is the input for the next two models age and emotion recognition. 

How does it splits the requests to the next two models.? Because both models are using same inputs as [10 , 1 ,64 , 64 , 3]. I am a very confused at this stage.

It does splits 5 requests to each model or it splits 10 to each model.?
Looking for response.

![people1](https://user-images.githubusercontent.com/57169077/125195711-79a6f280-e274-11eb-8aaf-8891608d597b.jpeg)

Thanks.

**Comment by atobiszei** [comment]
Hi @bhargav-sudo

> Note : I had changed **demultiply_count from 0 to 10** in **config.JSON** file for better understanding of shapes of input and output of a node. It does works after change to 10.

Yes that change works but only if you sent images that detect exactly 10 faces. If you will be sending images that will have varied number of detections you need to set `demultiply_count=0`


> After completion of face_detection node and the custom node we are resizing the face_Image to the shape of **[10 , 1 , 64 , 64 , 3]** and this shape is the input for the next two models age and emotion recognition.
> 
> How does it splits the requests to the next two models.? Because both models are using same inputs as [10 , 1 ,64 , 64 , 3]. I am a very confused at this stage.
> 
> It does splits 5 requests to each model or it splits 10 to each model.?

Custom node prepares the output in the shape `[detectionCount, 1, 64, 64, 3]`. Then when pipeline receives such output demultiplexer divides it into 10 requests for following nodes with shape [1, 64, 64, 3]. Each of following nodes receives each cropped face image.

Then at the gathering node (exit node if not specified) it will gather the results from the previous demultiplication. So in the case of face_coordinates output it will merge 10x (1, 4) into (10,1,4).

**Comment by bhargav-sudo** [comment]
hi @atobiszei 

Thanks for the response.

So, you are saying that for the other two nodes **after extract_node** which are age_gender and emotion_recognition will receive 10 requests each.

For 1 request each it will get 1 each cropped image which are in 64x64 width and height. 
And I need to know first it will go into **age_gender** and **emotion_recognition models.** 
Am I correct..?

Thanks.

**Comment by atobiszei** [comment]
I think that image in our docs may be slightly misleading

> For 1 request each it will get 1 each cropped image which are in 64x64 width and height.
> And I need to know first it will go into **age_gender** and **emotion_recognition models.**
> Am I correct..?

From 1 source image custom node will extract N face images. Then each one will go into **age_gender** and **emotion_recognition** model.

> The output of **face coordinates and face_confidence levels** after custom node will directly goes to gather node if specified other wise it will directly goes to response node

I think that image in our docs may be slightly misleading here. In both cases the results of inferences will be gathered in response node.

**Comment by bhargav-sudo** [comment]
Hi @atobiszei 

Thanks for the response.
Assume there are 10 requests (requests = extracted N face images) from 1 source image.
So the server will get a total of **10 requests** or the **10 requests** goes as only 1 request to the server...?
Thnks.

**Comment by atobiszei** [comment]
I am not sure I understand the question.

Assuming you send picture on which we have 9 faces:

You send 1 predict request, then when custom node extracts those 9 images each one of them is "sent" to following nodes and executed in parallel (so each following node performs 9 separate inferences). Then just before sending the response back gathering is performed of all responses and we send 1 response.

**Comment by bhargav-sudo** [comment]
I need to know whether the 9 separate inferences sent as 1 request to the next node or
We are sending as 9 requests.

**Comment by atobiszei** [comment]
9 passes with 1 image each.

**Comment by bhargav-sudo** [comment]
Hi @atobiszei 
I thought It was as **1 pass with 9 images** each.
