### ISSUE TITLE
make docker_build BASE_OS=ubuntu build model server with ubuntu error

### ISSUE THREAD

**Issue by zhaohb** [openvinotoolkit/model_server#846]
now I want to build model server with ubuntu, I am using revert_ubuntu, but I can not build success.
what can I do if I want build model server with ubuntu?

> error output:

```shell
......
ERROR: /ovms/src/BUILD:17:11: C++ compilation of rule '//src:ovms_lib' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 269 argument(s) skipped)
src/customnodesession.cpp: In member function 'ovms::Status ovms::CustomNodeSession::createBlob(const CustomNodeTensor*, InferenceEngine::Blob::Ptr&, const ovms::NodeLibrary&)':
......
```

**Comment by dtrawins** [comment]
@zhaohb official support for ubuntu will be announced and merged to `main` branch in ~2 weeks.
For now you can try building ovms with ubuntu base os from `develop` branch. Have in mind this branch is still under development and testing.
