### ISSUE TITLE
the calculation of the FullyConnected layer takes a lot of time

### ISSUE THREAD

**Issue by zhaohb** [openvinotoolkit/model_server#887]
now I have a model, and I've pressed it with benchmark and found that the FullyConnected layer takes a lot of time，about 25% of the total inference time：
```shell
dense/BiasAdd                 EXECUTED       layerType: FullyConnected     realTime: 4481      cpu: 4481           execType: jit_gemm_FP32
...
dense_2/BiasAdd               EXECUTED       layerType: FullyConnected     realTime: 4490      cpu: 4490           execType: jit_gemm_FP32
...
```
In this link [https://toscode.gitee.com/vinsonSpace/openvino/blob/master/build-instruction.md](https://toscode.gitee.com/vinsonSpace/openvino/blob/master/build-instruction.md) saw that GEMM can be accelerated through openblas or MKL：

![image](https://user-images.githubusercontent.com/5791375/131117245-5dfd1723-836f-4db8-9d5d-e7777a7ac19b.png)

I want to use mkl:
```shell
cmake ..     -DENABLE_CLDNN=OFF     -DENABLE_OPENCV=OFF     -DENABLE_VPU=OFF     -DENABLE_PYTHON=ON    -DNGRAPH_ONNX_IMPORT_ENABLE=ON -DNGRAPH_ONNX_FRONTEND_ENABLE=ON  -DNGRAPH_ONNX_EDITOR_ENABLE=ON  -DGEMM=MKL -DMKLROOT=/work/compile_ov_20214/mklml_lnx_2019.0.5.20190502  -DCMAKE_INSTALL_PREFIX=/work/compile_ov_20214/openvino_dist
```
but I am reminded that this GEMM macro is not available. 
```shell
CMake Warning:
  Manually-specified variables were not used by the project:

    GEMM
    DMKLROOT
......
```
openvino doesn't support this macro？

**Comment by mzegla** [comment]
This issue is not related to the model server, but OpenVINO itself.
I can see the thread is continued in https://github.com/openvinotoolkit/openvino/issues/7273, so I'm closing this one.
