### ISSUE TITLE
use model server gRPC api from gstreamer pipeline

### ISSUE THREAD

**Issue by wfchair** [openvinotoolkit/model_server#891]
I want to call model server gRPC api from sink or src pad of some gstreamer pipeline element:

pad.add_probe(Gst.PadProbeType.BUFFER, pad_probe_callback)
...
frame = VideoFrame(buffer, caps=caps)

how can I prepare request img data from frame.data?

request = predict_pb2.PredictRequest()
request.inputs["data"].CopyFrom(make_tensor_proto(img, shape=(img.shape)))

**Comment by mzegla** [comment]
I believe that's right. If `frame.data()` is a numpy array then it can be used similar to what you wrote:

```
request = predict_pb2.PredictRequest()
request.inputs["data"].CopyFrom(make_tensor_proto(img, shape=(img.shape)))
```
Keep in mind that the request you send must match the model you use. So if your frame is 512x512 and the model accepts images of size 300x300, then you might need to resize it before sending to OVMS. 
Also, most models that process images have certain layout defined (NHWC, NCHW) where:
N - batch size
C - color channels
H - image height
W - image width 

So your model might take inputs of shape (1,3,300,300). The frame you have might have different layout (1,300,300,3) or might not contain batch size dimension (3,300,300). Before creating the request make sure the numpy array you have matches the model input.
