### ISSUE TITLE
New Сore for each model in "--config_path config.json" instead of one Core for all.

### ISSUE THREAD

**Issue by DmitryCS** [openvinotoolkit/model_server#914]
<b>I had a task to figure out the reason for the impossibility of launching several models on one NCS2 using model_server. </b>

I have run different configurations with multiple models on different devices. Everything worked except running two models on the MYRIAD device. The following error was issued by the docker server for the second model on MYRIAD:
`modelinstance.cpp: 394 (Cannot load network into target device; error: Can not init Myriad device: NC_ERROR; model: person-detection; version: 1; device: MYRIAD)`
After that I decided to understand why I can use several models on MYRIAD using OpenVINO. I found that for the MYRIAD device there can be only one IECore with the models loaded into it for all programs. That is, if you run the same program at the same time in different terminals on MYRIAD device, then only the first will be executed, and the second will not be able to load the model into the device an error will be issued:
`[ERROR] Can not init Myriad device: NC_ERROR`
I was looking for the problem in the model_server source. So, I found that for each model in config.json, its own object of the ModelInstance class is created, which has the attribute 
   `std::unique_ptr<InferenceEngine::Core> engine;`
but as mentioned above, MYRIAD can work with only one Core with models loaded into it at a time.

<h3><b>Accordingly, the questions arise:
<br>1. For what reasons do you create Inference Engine Core for each model? 
<br>2. What prevents the implementation of one common?
<br>3. Would a common core make it possible to use multiple models on one Neural Compute Stick 2?</b></h3>

**Comment by mzegla** [comment]
Thank you for investigating this issue. Answering your questions:
 1. There's no particular reason for that. We didn't experience any issues with having IECore per model instance so far. 
 2. It's hard to tell right away. We will investigate using one common Core for all models in OVMS as it seems reasonable to do 
 and see if there would be any issues with applying such change. 
 3. It's also hard to tell. We have tests that load more than one model into the NCS2 and they work fine, so first we would need to reproduce your issue, switch OVMS to use one Core and check if that helps. 

By the way, could you share more details about your setup?
- what hardware are you running on?
- what models do you use? (in this case I'm particularly interested in their size)
- how do you run OVMS? (configuration file and a command you use to launch it)

**Comment by DmitryCS** [comment]
I guess you have tests with loading several models into the NCS2 using OpenVino, not model_server. For example, demos of OpenVINO like `python3 sample.py -m_1 alexnet.xml -m_2 caffenet.xml -d MYRIAD` will work correctly, since the models are loaded into one IECore inside the script. But if you use two IECore, each model has its own IECore, then the first model will be loaded, and the second will not be able to load into MYRIAD, which is what happens in model_server. Also your [manual](https://github.com/openvinotoolkit/model_server/blob/main/docs/docker_container.md#user-content-start-the-server-with-an-intel-movidius-neural-compute-stick) for NCS2 on model_server says the following: "A single stick can handle one model at a time. If there are multiple sticks plugged in, OpenVINO Toolkit chooses to which one the model is loaded."<br>
Details about my setup and how to reproduce the situation:
1. Hardware (lspci):
![Screenshot from 2021-09-09 15-41-07](https://user-images.githubusercontent.com/46371199/132671855-5ef02290-cb16-4d62-bd46-a942f372c37f.png)
Stick (lsusb):
![Screenshot from 2021-09-09 15-50-12](https://user-images.githubusercontent.com/46371199/132673037-a472454f-e1b5-4e95-82a4-6c0dd6e99bb1.png)

2. For example, Alexnet FP16 and Caffenet FP16. 
3. Models directory tree:
models/
├── alexnet
│────└── FP16
│────────└── 1
│ ───────────├── alexnet.bin
│ ───────────├── alexnet.mapping
│ ───────────└── alexnet.xml
├── caffenet
│────└── FP16
│────────└── 1
│───────────├── caffenet.bin
│───────────├── caffenet.mapping
│───────────└── caffenet.xml
└── config.json
<br> Config.json content:
```
 {
   "model_config_list":[
      {
         "config":{
            "name":"alexnet",
            "base_path":"/opt/ml/alexnet/FP16",
            "batch_size": "auto",
            "target_device": "MYRIAD"
         }
      },
      {
         "config":{
            "name":"caffenet",
            "base_path":"/opt/ml/caffenet/FP16",
            "batch_size": "auto",
            "target_device": "MYRIAD"
         }
      }
   ]
}
```
Command to run:
```
docker run --rm -d -it --net=host --privileged \
--name test_myriad \
-v $(pwd)/models:/opt/ml \
-v /dev:/dev \
openvino/model_server \
--config_path /opt/ml/config.json \
--rest_port 8001
```
Check errors: <br>
`docker logs test_myriad | grep "\[error\]"`
<br>Docker logs will spam these errors over and over again:
```
[2021-09-09 12:10:10.076][1][serving][error][modelinstance.cpp:394] Cannot load network into target device; error: Can not init Myriad device: NC_ERROR; model: caffenet; version: 1; device: MYRIAD
[2021-09-09 12:10:10.076][1][serving][error][model.cpp:153] Error occurred while loading model: caffenet; version: 1; error: Cannot load network into target device
[2021-09-09 12:10:10.076][1][modelmanager][error][modelmanager.cpp:874] Error occurred while loading model: caffenet versions; error: Cannot load network into target device
[2021-09-09 12:10:16.130][60][serving][error][modelinstance.cpp:394] Cannot load network into target device; error: Can not init Myriad device: NC_ERROR; model: caffenet; version: 1; device: MYRIAD
[2021-09-09 12:10:16.130][60][serving][error][model.cpp:234] Error occurred while loading model: caffenet; version: 1; error: Cannot load network into target device
[2021-09-09 12:10:16.130][60][modelmanager][error][modelmanager.cpp:891] Error occurred while reloading model: caffenet; versions; error: Cannot load network into target device
```

**Comment by atobiszei** [comment]
I confirm that there is issue when trying to load more than 1 model on NCS with 2021.4.1 even when the model size is very small.

Working on a fix.
