### ISSUE TITLE
Can you tell me how to use many models in once post?

### ISSUE THREAD

**Issue by 17702513221** [openvinotoolkit/model_server#92]
like face-detection-retail,face-reidentification-retail,landmarks-regression-retail,l want to use it in once post ,so l want to ust custom bankgrand.

**Comment by mzegla** [comment]
You can serve multiple models by running model server with configuration file:
https://github.com/IntelAI/OpenVINO-model-server/blob/master/docs/docker_container.md#starting-docker-container-with-a-configuration-file

With single request you can run inference on a single model. If you want to run let's say, the same image on few models, you have to make separate requests for each model.

**Comment by chr15stevens** [comment]
Would be nice to have this feature. Would prevent a lot of round trips when running multiple models such as face detection then emotion detection.

**Comment by dtrawins** [comment]
@17702513221 @chr15stevens This functionality has been added to the latest release 2021.1. Now you could create any pipelines of models for a single request. You can check the [model ensemble](https://github.com/openvinotoolkit/model_server/blob/main/docs/ensemble_scheduler.md) example.
