### ISSUE TITLE
Could you support dynamic input?

### ISSUE THREAD

**Issue by liiitleboy** [openvinotoolkit/model_server#937]
Image models with dynamic input hope to be supported

**Comment by mzegla** [comment]
Currently such feature is not supported in OpenVINO. When it gets enabled in OV, we will support it in the model server.

**Comment by liiitleboy** [comment]
> Currently such feature is not supported in OpenVINO. When it gets enabled in OV, we will support it in the model server.

Is there an approximate due time

**Comment by mzegla** [comment]
I think you would get the best answer to that question from OpenVINO Core team. Please ask this on OpenVINO repository:
https://github.com/openvinotoolkit/openvino
