### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Shwetaspc** [openvinotoolkit/model_server#943]
With the quick start guide I am able to add my own client to this model. How Can I modify the server model to customize?

**Comment by rasapala** [comment]
@Shwetaspc Hi, can you provide more details what modifications you would like to make ?

**Comment by Shwetaspc** [comment]
I want to modify .proto files and define custom GRPC API's.
Ex; We already have predict GRPC API for face - detection module.
Similary I want to add few GRPC API's for my social distancing module.

**Comment by mzegla** [comment]
Well, you will need to look deeply at the flows in the model server to see exactly what you need to modify to add custom API. 
You could add a service with your custom API here: https://github.com/openvinotoolkit/model_server/blob/main/src/server.cpp#L194-L195.
If you choose to modify or base on existing PredictionService, you would need to adjust it to work with your custom objects for requests and responses:
https://github.com/openvinotoolkit/model_server/blob/main/src/prediction_service.cpp#L65

If you look at the implementation of this service you can see that data in the request is used both for getting the right model and running prediction, so your request need to contain data as well as information about the model - model name and model version. In other methods you will need to extract it and use it to get the right ModelInstance. 

For simple inference you will need to make infer() method work with your API - https://github.com/openvinotoolkit/model_server/blob/main/src/modelinstance.cpp#L994 
That includes changing request validation, deserialization and serialization. 

Adding custom API or modifying existing is quite a big task, so make sure you understand how the model server works internally before making changes, if you want to use your customized version in production environment.

**Comment by dtrawins** [comment]
@Shwetaspc Why the API changes are needed? Perhaps you have in mind just using different model with different input and outputs. For that, there is not need to change the API and proto definition. It is generic so it can support arbitrary model and use case.
